---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/11/01 16:23
--- Describe:
---

---@class BoundaryTriggerActionCtrlBase : table
BoundaryTriggerActionCtrlBase = class(nil, "BoundaryTriggerActionCtrlBase")

---@public
---@param _triggerCom BattleObjCom_BoundaryTrigger 
function BoundaryTriggerActionCtrlBase:Init(_triggerCom)
	self:__Init(_triggerCom)
end

---@protected
---@param _triggerCom BattleObjCom_BoundaryTrigger
function BoundaryTriggerActionCtrlBase:__Init(_triggerCom)
	self.__triggerCom = _triggerCom
	self.__enterActions_1 = {}
	self.__enterActions_2 = {}
	self.__stayActions = {}
	self.__leaveActions_1 = {}
	self.__leaveActions_2 = {}
end

---@public
function BoundaryTriggerActionCtrlBase:TrigEnter_1(_netIdList, _deltaTime)
	--LogTools.LogByLevel(LogLevel.log, "CheckArea", "BoundaryTriggerActionCtrlBase TrigEnter_1 start", "self.__enterActions_1", #self.__enterActions_1)
	for i = 1, #self.__enterActions_1 do
		self.__enterActions_1[i]:Trig(_netIdList, _deltaTime)
	end
end

---@public
function BoundaryTriggerActionCtrlBase:TrigEnter_2(_netIdList, _deltaTime)
	--LogTools.LogByLevel(LogLevel.log, "CheckArea", "BoundaryTriggerActionCtrlBase TrigEnter_2 start", "self.__enterActions_2", #self.__enterActions_2)
	for i = 1, #self.__enterActions_2 do
		self.__enterActions_2[i]:Trig(_netIdList, _deltaTime)
	end
end

---@public
function BoundaryTriggerActionCtrlBase:TrigStay(_netIdList, _deltaTime)
	for i = 1, #self.__stayActions do
		self.__stayActions[i]:Trig(_netIdList, _deltaTime)
	end
end

---@public
function BoundaryTriggerActionCtrlBase:TrigLeave_1(_netIdList, _deltaTime)
	--LogTools.LogByLevel(LogLevel.log, "CheckArea", "BoundaryTriggerActionCtrlBase TrigLeave_1 start", "self.__leaveActions_1", #self.__leaveActions_1)
	for i = 1, #self.__leaveActions_1 do
		self.__leaveActions_1[i]:Trig(_netIdList, _deltaTime)
	end
end

---@public
function BoundaryTriggerActionCtrlBase:TrigLeave_2(_netIdList, _deltaTime)
	--LogTools.LogByLevel(LogLevel.log, "CheckArea", "BoundaryTriggerActionCtrlBase TrigLeave_2 start", "self.__leaveActions_2", #self.__leaveActions_2)
	for i = 1, #self.__leaveActions_2 do
		self.__leaveActions_2[i]:Trig(_netIdList, _deltaTime)
	end
end

---@public
---@return BattleObjCom_BoundaryTrigger
function BoundaryTriggerActionCtrlBase:GetTriggerCom()
	return self.__triggerCom
end

---@public
---@return BattleRoom
function BoundaryTriggerActionCtrlBase:GetBattleRoom()
	return self.__triggerCom.battleRoom
end

---@public
function BoundaryTriggerActionCtrlBase:OnOpen()

end

---@public
function BoundaryTriggerActionCtrlBase:OnClose()
	
end

---@public
function BoundaryTriggerActionCtrlBase:OnDestroy()

end

---@public
function BoundaryTriggerActionCtrlBase:Clear()
	self:__Clear()
end

---@protected
function BoundaryTriggerActionCtrlBase:__Clear()
	self.__triggerCom = nil
	for _, _action in pairs(self.__enterActions_1) do
		_action:Clear()
	end
	self.__enterActions_1 = nil
	for _, _action in pairs(self.__enterActions_2) do
		_action:Clear()
	end
	self.__enterActions_2 = nil
	for _, _action in pairs(self.__stayActions) do
		_action:Clear()
	end
	self.__stayActions = nil
	for _, _action in pairs(self.__leaveActions_1) do
		_action:Clear()
	end
	self.__leaveActions_1 = nil
	for _, _action in pairs(self.__leaveActions_2) do
		_action:Clear()
	end
	self.__leaveActions_2 = nil
end

return BoundaryTriggerActionCtrlBase