---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/3/16 16:43

---- 枚举
---@class LevelUnitStateEnum
---@type number 枚举映射
LevelUnitStateEnum = {
    ---@type LevelUnitStateEnum 初始状态：仅从编辑器加载出来
    INITIAL = 1,
    ---@type LevelUnitStateEnum 激活状态：创建出了单位实体
    ACTIVE = 2,
    ---@type LevelUnitStateEnum 死亡状态：创建出实体，并死亡
    DEAD = 3,
}