---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/3/16 17:12

require "Lib/class"

---@class LevelUnitType : table
---@field id number
---@field func function
LevelUnitType = class(nil, 'LevelUnitType');

function LevelUnitType:ctor(_id, _func)
    self.id = _id;
    self.func = _func;
end

---@public
function LevelUnitType:GetId()
    return self.id
end

---@public
---@return LevelUnitBase
function LevelUnitType:CreateLevelUnit()
    if not self.func then
        return
    end
    ---@type LevelUnitBase
    local unitBase = self.func()
    return unitBase
end

return LevelUnitType;
