---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2023/07/28 14:37
--- Describe:
---

---@class RogueUnitSkillEffectBase : table
RogueUnitSkillEffectBase = class(nil, "RogueUnitSkillEffectBase")
function RogueUnitSkillEffectBase:ctor(_data) end

---@public
---@return BattleRoom
function RogueUnitSkillEffectBase:GetBattleRoom()
	return self.__battleRoom
end

---@public
---@return number
function RogueUnitSkillEffectBase:GetBattleId()
	return self.__battleId
end

---@public
---@return BattleUnitBase
function RogueUnitSkillEffectBase:GetUnit()
	return self.__action:GetUnit()
end
------------------------------------------------------------------------------------------------------------------------

---@protected
---@param _action RogueUnitSkillActionBase
---@param _xls RogueUnitSkillEffect
function RogueUnitSkillEffectBase:__Init(_action, _xls)
	if CheckLogLevel(LogLevel.log) and LogTools.RogueUnitSkillLog then
		LogTools.LogByLevel(LogLevel.log, "肉鸽主公技", "    Effect初始化开始", "Effect Id", _xls.id, "Effect 类型", LogTools.GetEnumTableDesc(Enum_RogueUnitSkillEffectType, _xls.effectType), "所属Action", _action:GetId())
	end
	---@protected
	---@type RogueUnitSkillActionBase
	self.__action = _action
	---@protected
	---@type BattleRoom
	self.__battleRoom = _action:GetBattleRoom()
	---@protected
	---@type number
	self.__battleId = _action:GetBattleId()
	---@protected
	---@type RogueUnitSkillEffect
	self.__xls = _xls
	---@protected
	---@type Enum_RogueUnitSkillEffectType
	self.__type = _xls.effectType
	
	if CheckLogLevel(LogLevel.log) and LogTools.RogueUnitSkillLog then
		LogTools.LogByLevel(LogLevel.log, "肉鸽主公技", "    Effect初始化结束", "Effect Id", _xls.id)
	end
end

---@public
---@param _action RogueUnitSkillActionBase
---@param _xls RogueUnitSkillEffect
function RogueUnitSkillEffectBase:Init(_action, _xls)
	self:__Init(_action, _xls)
end

------------------------------------------------------------------------------------------------------------------------

---@protected
---@param _targetObjList BattleObjectBase[]
function RogueUnitSkillEffectBase:__OnTrig(_targetObjList)
end

---@public
function RogueUnitSkillEffectBase:OnTrig(_targetObjList)
	self:__OnTrig(_targetObjList)
end

---@protected
function RogueUnitSkillEffectBase:__OnRemove()
end

---@public
function RogueUnitSkillEffectBase:OnRemove()
	self:__OnRemove()
end


function RogueUnitSkillEffectBase:OnUpdate(_deltaTime)
end

------------------------------------------------------------------------------------------------------------------------

---@public
function RogueUnitSkillEffectBase:GetId()
	return self.__xls.id
end

---@public
---@return RogueUnitSkillEffect
function RogueUnitSkillEffectBase:GetXlsData()
	return self.__xls
end

---@public
---@return RogueUnitSkillActionBase
function RogueUnitSkillEffectBase:GetAction()
	return self.__action
end

---@public
function RogueUnitSkillEffectBase:GetEffectTypeDesc()
	return LogTools.GetEnumTableDesc(Enum_RogueUnitSkillEffectType, self.__type)
end

return RogueUnitSkillEffectBase