---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/2/17 15:10
---

luajava = {}

---@type function
---@param clzName string
function luajava.bindClass(clzName)
end

---@type function
---@param clzName string
function luajava.newInstance(clzName)
end

---@type function
---@param clzName string
function luajava.new(clzName)
end

---@type function
---@param clzName string
function luajava.createProxy(clzName)
end

---@type function
---@param clzName string
---@param methodName string
function luajava.loadLib(clzName, methodName)
end