---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2023-04-11 17:42:53
---
--- 通过Java工具类自动生成，请勿修改，重新生成会被覆盖
---

require "Lib/class"

---@class ServerDebugTool : table
ServerDebugTool = class(nil, 'ServerDebugTool');

function ServerDebugTool:ctor()
end

-- Lua断点调试工具
---@param tag string 断点标签
---@param condition any 断点条件
---@type function
---@return void
---@public
function ServerDebugTool:debug(tag, condition)
    return
end

return ServerDebugTool;
