---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/2/16 19:24
---
--- 服务端Lua战斗核心Java调用类com.biligame.access.service.TimeService的接口镜像

require "Lib/class"

---@class ServerTimeService : table
ServerTimeService = class(nil, 'ServerTimeService');

---@return ServerTimeServiceInstance
function ServerTimeService:getInstance()
    return nil
end

local ---@class ServerTimeServiceInstance : table
ServerTimeServiceInstance = class(nil, 'ServerTimeServiceInstance');

-- 获取服务器当前时间
---@public
function ServerTimeServiceInstance:now()
end

