---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2023-04-11 17:42:53
---
--- 通过Java工具类自动生成，请勿修改，重新生成会被覆盖
---

require "Lib/class"

---@class ServerLuaDict : table
ServerLuaDict = class(nil, 'ServerLuaDict');

function ServerLuaDict:ctor()
end

-- 根据表名和主键ID(Int)获取表luaTable
---@param name string 表名
---@param id number 表id
---@type function
---@return table
---@public
function ServerLuaDict:getLuaTableByNameAndIdInt(name, id)
    return
end

-- 根据表名和主键ID(String)获取表luaTable
---@param name string 表名
---@param id string 表id
---@type function
---@return table
---@public
function ServerLuaDict:getLuaTableByNameAndId(name, id)
    return
end

-- key是否存在
---@param name string 表名
---@param id number 表id
---@type function
---@return boolean
---@public
function ServerLuaDict:containsKeyByName(name, id)
    return
end

return ServerLuaDict;
