---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/3/16 17:18

require "Lib/class"

---@class LevelUnit_Monster : LevelUnitBase
---@field bossShow boolean Boss出场
LevelUnit_Monster = class(LevelUnitBase, 'LevelUnit_Monster');

function LevelUnit_Monster:ctor()

end

function LevelUnit_Monster:Init(_battleId, _unitData)
    self:__Init(_battleId, _unitData)
    self.bossShow = _unitData.bossShow
end

return LevelUnit_Monster;