---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2023/3/6 17:22

require "Lib/class"

---@class TalentSkillCreateDropObjectResult : table
TalentSkillCreateDropObjectResult = class(TalentSkillResultBase, 'TalentSkillCreateDropObjectResult');

function TalentSkillCreateDropObjectResult:ctor(_battleId)
    self.battleId = _battleId
    self.battleRoom = GetBattleRoom(self.battleId)
end

---触发被动技能
---@public
---@param _battleObjectBase BattleObjectBase
---@param _count number
---@param _talentSkillConfig TalentSkill
---@param _skillResult SkillResult
---@param _talentSkill BattlePlayerTalentSkill 被动技能
---@param _isReTrigger boolean 重新触发
function TalentSkillCreateDropObjectResult:Trigger(_battleObjectBase,_count,_talentSkillConfig,_skillResult,_talentSkill,_isReTrigger)
    local battleRoom = _battleObjectBase:GetBattleRoom()
    for objectId, count in pairs(_talentSkill.triggerTargetList) do
        ---@type BattleObjectBase
        local battleObject = battleRoom.battleObjectManager:GetObject(objectId);
        if battleObject then
            ---@type BattleUnitBase
            local targetUnit = battleObject:GetParentUnit();
            if targetUnit then
                local position = targetUnit:GetActionManager():GetPosition();
                for i = 1, _count do
                    battleRoom.fallObjectManager:DropFallObjectByPosition(_skillResult.parm1,_skillResult.parm2,targetUnit:GetNetId(),objectId,position,nil,_skillResult.parm4 == 1);
                end
            end
        end
    end
end

---被动技能触发类型
---@return number 被动技能触发类型
function TalentSkillCreateDropObjectResult:GetType()
    return 13;
end

return TalentSkillCreateDropObjectResult;