---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guokun.
--- DateTime: 2023/1/5 18:02

require "Lib/class"
require "Battle/Logic/Room/BattleLogicEvent/BattleLogicEventV2"

---@class BattleLogicChangeStateEvent : BattleLogicEventV2
---@field eventType number 事件类型
---@field battleId number 战斗id
---@field eventCompareParam table 事件参数
---@field eventTriggerParam table 事件透传参数
---@field netId number 事件产出单位Id
---@field objectId number 事件产出物体Id
BattleLogicChangeStateEvent = class(BattleLogicEventV2, 'BattleLogicChangeStateEvent');

---@param _eventType number 事件类型
---@param _battleId number 战斗id
---@param _eventCompareParam table 事件参数
---@param _eventTriggerParam table 事件透传参数
---@param _netId number 事件产出单位Id
---@param _objectId number 事件产出物体Id
function BattleLogicChangeStateEvent:ctor(_eventType, _eventCompareParam, _eventTriggerParam, _netId, _objectId, _battleId)
    self.battleId = _battleId
    self.eventType = _eventType;
    self.eventCompareParam = _eventCompareParam;
    self.eventTriggerParam = _eventTriggerParam;
    self.netId = _netId;
    self.objectId = _objectId;
    self.survival = 0;
end

---检测事件触发，默认没有比较参数
---@public
---@param _eventCompareParam table 比较参数
function BattleLogicChangeStateEvent:CheckEventTrigger(_eventCompareParam)
    if self.eventCompareParam and self.eventCompareParam.stateId == _eventCompareParam.stateId and self.eventCompareParam.isLeave == _eventCompareParam.isLeave then
        return true
    end
    return false
end

---事件回调，默认为空
---@public
function BattleLogicChangeStateEvent:FireEvent()

end

---@public
---检测互斥事件
---@param _event BattleLogicEventV2 新事件
---@return boolean 是否互斥
function BattleLogicChangeStateEvent:CheckMutexEvent(_event)
    return false;
end

---检测移除事件，默认事件会在trigger之后的下一帧被移除
---@public
function BattleLogicChangeStateEvent:CheckRemoveEvent()
    self.survival = self.survival + 1;
    if self.survival > 1 then
        return true;
    end
    return false;
end

---生成比较参数
---@public
function BattleLogicChangeStateEvent:GenerateCompareParam(_param);
    local compareParam = {};
    return compareParam;
end

return BattleLogicChangeStateEvent;