---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2023/7/28 16:01

require "Lib/class"
require "Battle/Logic/Skill/SkillBaseNode"

---@class SkillCheckCollideNode : SkillBaseNode
---@field nodeId number 节点id
---@field nextNodes SkillNodeExitData[] 子节点
SkillCheckCollideNode = class(SkillBaseNode, 'SkillCheckCollideNode');

---@param _nodeId number 节点id
---@param _once boolean 只执行一次
---@param _nextNodes SkillNodeExitData[] 子节点
---@param _specialExit SkillNodeExitData[] 特殊出口
function SkillCheckCollideNode:ctor(_nodeId, _once, _nextNodes, _specialExit,_buffIds)
    self.nodeId = _nodeId;
    self.once = _once;
    self.nextNodes = _nextNodes;
    self.specialExit = _specialExit;
    self.buffIds = _buffIds;
end

---执行技能节点
---@param _actionStateManager ActionStateManage 行为管理器
---@param _dt number 更新时间
---@param _netId number 单位id
---@param _skillModel SkillModel 技能配置
---@return boolean,table 是否执行结束,执行行为输出数据
function SkillCheckCollideNode:DoAction(_actionStateManager, _dt, _netId, _skillModel,_currentSkillState)
    if not _currentSkillState.checkCollider then
        return true,nil;
    end
    if _actionStateManager:GetUnit():GetBattleRoom().battleLogicEventService:CheckUnitCollideEvent(_netId) then
        ---@type BattleObjCom_Buff
        local buffCompo = _actionStateManager:GetUnit():GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Buff);
        if buffCompo == nil then
            return true,nil;
        end
        for i, v in pairs(self.buffIds) do
            ---@type BuffGroup
            local addBuffGroup = _actionStateManager.battleRoom.inputDataSource:GetDict("BuffGroup",tonumber(v))
            if addBuffGroup == nil then
                return true,nil;
            end
            local battleBuffCastTemplate = BattleBuffService:GenerateCastBuffTemplate(tonumber(v),_actionStateManager:GetUnit():GetCurrentHeroObject(),_skillModel.skillId,nil)
            buffCompo:AddBattleBuff(battleBuffCastTemplate);
        end
        return true,nil;
    end
    return false,nil;
end

---返回节点类型
---@public
---@return number 节点类型
function SkillCheckCollideNode:GetType()
    return 71;
end

return SkillCheckCollideNode;