---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2022/4/14 12:04

require "Lib/class"
require "Battle/Logic/Skill/SkillBaseNode"

---@class SkillLoopStartNode : SkillBaseNode 技能循环开始节点
---@field nodeId number 节点id
---@field nextNodes SkillNodeExitData[] 子节点
SkillLoopStartNode = class(SkillBaseNode, 'SkillLoopStartNode');

---@param _nodeId number 节点id
---@param _once boolean 只执行一次
---@param _nextNodes SkillNodeExitData[] 子节点
---@param _specialExit SkillNodeExitData[] 特殊出口
function SkillLoopStartNode:ctor(_nodeId,_once, _nextNodes,_specialExit,_loopId,_loopDelayTime)
    self.nodeId = _nodeId;
    self.once = _once;
    self.nextNodes = _nextNodes;
    self.specialExit = _specialExit;
    self.loopId = _loopId;
    self.loopDelayTime =  _loopDelayTime * 1000;
end

---执行技能节点
---@param _actionStateManager ActionStateManage 行为管理器
---@param _dt number 更新时间
---@param _netId number 单位id
---@param _skillModel SkillModel 技能配置
---@param _currentSkillState SkillActionState 当前技能状态
---@return boolean,table 是否执行结束,执行行为输出数据
function SkillLoopStartNode:DoAction(_actionStateManager, _dt, _netId,_skillModel,_currentSkillState)
    if not _currentSkillState.loopInfos[self.loopId] then
        _currentSkillState.loopInfos[self.loopId] = 0;
    end
    if _currentSkillState.loopInfos[self.loopId] > 0 then
        local runTime = TimeUtils.battleNow(_actionStateManager.battleId) - _currentSkillState.nodeStartRunTimes[self.nodeId];
        if runTime < self.loopDelayTime then
            return false,nil;
        end
    end
    _currentSkillState.loopInfos[self.loopId] = _currentSkillState.loopInfos[self.loopId] + 1;
    return true, nil;
end

---返回节点类型
---@public
---@return number 节点类型
function SkillLoopStartNode:GetType()
    return 31;
end

return SkillLoopStartNode;