---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/04/09 14:56
--- Describe: 触发器生命周期管理
---

require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeConditionBase"
require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeCondition_Immediately"
require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeCondition_TrigTimes"
require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeCondition_WaitSecAfterCreated"
require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeCondition_WaitSecAfterOpened"
require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeCondition_SubordinationObjDead"
require "Battle/Logic/Room/BattleObject/BoundaryTrigger/TriggerLife/AreaTrigger/AreaTriggerLifeCondition_SubordinationUnitDead"

---生命周期条件类型
---@class AreaTriggerLifeConditionType : table
AreaTriggerLifeConditionType = {
	Immediately = 1,               --立刻
	Never = 2,                     --永不
	WaitSecondsAfterCreated = 3,   --创建后等待X秒开启
	WaitSecondsAfterOpened = 4,    --开启后等待X秒开启
	OnTriggerTimes = 5,            --触发达到一定次数
	SubordinationObjDead = 6,      --创建者英雄死亡
	SubordinationUnitDead = 7,      --创建者unit死亡
}

---@class AreaTriggerLifeConditionCtrl : BoundaryTriggerLifeConditionCtrlBase
AreaTriggerLifeConditionCtrl = class(BoundaryTriggerLifeConditionCtrlBase, "AreaTriggerLifeConditionCtrl")

---@public
---@param _triggerCom BattleObjCom_BoundaryTrigger
function AreaTriggerLifeConditionCtrl:Init(_triggerCom, _dicIdList)
	--LogTools.LogByLevel(LogLevel.log, "CheckArea", "AreaTriggerLifeConditionCtrl Init start", "_dicIdList", dumpTableEx(_dicIdList))
	self:__Init(_triggerCom)
	
	---@type BattleObjCom_AreaTrigger
	self.__areaCom = _triggerCom:GetObject():GetComponent(BattleObjectComponentType.AreaTrigger)
	for i = 1, #_dicIdList do
		self:__InitLifeCondition(_dicIdList[i])
	end
end

---初始化开始条件和关闭条件
---@private
function AreaTriggerLifeConditionCtrl:__InitLifeCondition(_dicId)
	---@type AreaColliderLifeCtrl
	local _xls = self:GetBattleRoom().inputDataSource:GetDict("AreaColliderLifeCtrl", _dicId)
	
	---开启条件
	---@private
	---@type AreaTriggerLifeConditionBase
	local _openCondition = AreaTriggerLifeConditionCtrl.__GetLifeCondition(_xls.openType)
	if LogTools.AreaLog and CheckLogLevel(LogLevel.log) then
		LogTools.LogByLevel(LogLevel.log, "CheckArea", "AreaTriggerLifeConditionCtrl Init start", "_xls.openType", _xls.openType, "_openCondition", _openCondition)
	end
	if _openCondition then
		_openCondition:Init(self, _xls.openParamFloat, _xls.openParamString)
		table.insert(self.__openConditions, _openCondition)
	end
	
	---关闭条件
	---@private
	---@type AreaTriggerLifeConditionBase
	local _closeCondition = AreaTriggerLifeConditionCtrl.__GetLifeCondition(_xls.closeType)
	if LogTools.AreaLog and CheckLogLevel(LogLevel.log) then
		LogTools.LogByLevel(LogLevel.log, "CheckArea", "AreaTriggerLifeConditionCtrl Init start", "_xls.closeType", _xls.closeType, "_closeCondition", _closeCondition)
	end
	if _closeCondition then
		_closeCondition:Init(self, _xls.closeParamFloat, _xls.closeParamString)
		table.insert(self.__closeConditions, _closeCondition)
	end
end

---@private
---@return AreaTriggerLifeConditionBase
function AreaTriggerLifeConditionCtrl.__GetLifeCondition(_type)
	--LogTools.LogByLevel(LogLevel.log, "CheckArea", "AreaTriggerLifeConditionCtrl __GetLifeCondition start", "_type", LogTools.GetEnumTableDesc(AreaTriggerLifeConditionType, _type))
	---@type AreaTriggerLifeConditionBase
	local _condition = nil
	if _type == AreaTriggerLifeConditionType.Immediately then
		_condition = AreaTriggerLifeCondition_Immediately.New()
	elseif _type == AreaTriggerLifeConditionType.Never then
		--_condition = AreaTriggerLifeCondition_Never.New()
	elseif _type == AreaTriggerLifeConditionType.WaitSecondsAfterCreated then
		_condition = AreaTriggerLifeCondition_WaitSecAfterCreated.New()
	elseif _type == AreaTriggerLifeConditionType.WaitSecondsAfterOpened then
		_condition = AreaTriggerLifeCondition_WaitSecAfterOpened.New()
	elseif _type == AreaTriggerLifeConditionType.OnTriggerTimes then
		_condition = AreaTriggerLifeCondition_TrigTimes.New()
	elseif _type == AreaTriggerLifeConditionType.SubordinationObjDead then
		_condition = AreaTriggerLifeCondition_SubordinationObjDead.New()
	elseif _type == AreaTriggerLifeConditionType.SubordinationUnitDead then
		_condition = AreaTriggerLifeCondition_SubordinationUnitDead.New()
	end
	
	return _condition
end

------------------------------------------------------------------------------------------------------------------------

---@protected
function AreaTriggerLifeConditionCtrl:__TrigWaitDestroy()
	self.__state = BoundaryTriggerLifeState.WaitDestroy
	---@type BattleObjectBase
	local _belongObj = self.__triggerCom:GetObject()
	self:GetBattleRoom().battleUnitManager:OnBattleObjectDead(_belongObj:GetParentUnit():GetNetId(), _belongObj:GetObjectId(), LuaBehav_Define_DeadType.DeadSilence)
end

---@public
function AreaTriggerLifeConditionCtrl:OnOpen()
	self.__state = BoundaryTriggerLifeState.Opened
	self.__areaCom:OnOpen()
end

---@public
function AreaTriggerLifeConditionCtrl:OnClose()
	self.__state = BoundaryTriggerLifeState.Closed
	self.__areaCom:OnClose()
end

---@public
function AreaTriggerLifeConditionCtrl:OnDestroy()
	self.__areaCom:OnDestroy()
end

---@public
function AreaTriggerLifeConditionCtrl:Clear()
	self.__areaCom = nil
	self:__Clear()
end
return AreaTriggerLifeConditionCtrl