---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/04/09 17:54
--- Describe: 开启后等待X秒
---

---@class AreaTriggerLifeCondition_WaitSecAfterOpened : AreaTriggerLifeConditionBase
AreaTriggerLifeCondition_WaitSecAfterOpened = class(AreaTriggerLifeConditionBase, "AreaTriggerLifeCondition_WaitSecAfterOpened")
function AreaTriggerLifeCondition_WaitSecAfterOpened:Init(_lifeConditionCtrl, _floatParam, _strParam)
	self:__Init(_lifeConditionCtrl, _floatParam, _strParam)
	self.__startTime = _lifeConditionCtrl:GetTimeStamp()
	self.__battleId = _lifeConditionCtrl:GetBattleRoom().battleId
	self.__timeTotal = self.__floatParam * 1000
end

function AreaTriggerLifeCondition_WaitSecAfterOpened:OnUpdate(_deltaTime)
	if not self.__lifeConditionCtrl:CheckState(BoundaryTriggerLifeState.Opened) then return false end
	if TimeUtils.battleNow(self.__battleId) - self.__startTime < self.__timeTotal then return false end
	return true
end

function AreaTriggerLifeCondition_WaitSecAfterOpened:ChangeTimeTotal(_changeValue)
	self.__timeTotal = self.__timeTotal + _changeValue * 1000
	if self.__timeTotal < 0 then self.__timeTotal = 0 end
end

function AreaTriggerLifeCondition_WaitSecAfterOpened:ChangeTimeAcc(_changeValue)
	self.__timeAcc = self.__timeAcc + _changeValue * 1000
end

function AreaTriggerLifeCondition_WaitSecAfterOpened:Clear()
	self.__startTime = nil
	self.__battleId = nil
	self.__timeTotal = nil
	self:__Clear()
end
return AreaTriggerLifeCondition_WaitSecAfterOpened