---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wth.
--- DateTime: 2021/12/14 14:53
---

---@class LogTools : table
LogTools = {}

if IsServer() then
    ServerLogTool = luajava.bindClass("com.biligame.access.luaj.log.LuaLogTool")
    LogStyle = luajava.bindClass("com.biligame.access.log.LogStyle")
end

function LogTools.P(tag, ...)
    local tbl = { ... }
    local max = select("#", ...)
    local str = ""
    if IsClient() then
        str = tostring("<color=#00FF00>[" .. tostring(tag) .. "]</color>")
        for i = 1, max do
            str = str .. ", " .. tostring(tbl[i])
        end
    else
        str = tostring(tostring(tag))
        for i = 1, max do
            str = str .. ", " .. tostring(tbl[i])
        end
        str = tostring(LogStyle.BG_GREY:formatString(tostring(str)))
    end
    return str
end

function LogTools.GetTraceback(str)
    if IsClient() then
        return str .. "\n" .. debug.traceback(self, 10) .."\n" .."LogTools.GetTraceback end" .."\n"
    else
        return ServerLogTool:traceback(str)
    end
end

function LogTools.Debug(tag, ...)
    local logMsg = LogTools.GetTraceback(LogTools.P(tag, ...))
    if IsClient() then
        print(logMsg)
    else
        ServerLogTool:log(LogLevel.log, logMsg)
    end
end

function LogTools.Error(tag, ...)
    local logMsg = LogTools.GetTraceback(LogTools.P(tag, ...))
    if IsClient() then
        logError(logMsg)
    else
        ServerLogTool:log(LogLevel.logErr, logMsg)
    end
end

function LogTools.Info(tag, ...)
    local logMsg = LogTools.P(tag, ...)
    if IsClient() then
        print(logMsg)
    else
        ServerLogTool:log(LogLevel.log, logMsg)
    end
end

function LogTools.LogByLevel(_logLevel, ...)
    if _logLevel == LogLevel.log then
		LogTools.Info( ...)
	elseif _logLevel == LogLevel.logAss then
		LogTools.log(...)
	--elseif _logLevel == LogLevel.logWarr then
	--	
	elseif _logLevel == LogLevel.logErr then
		LogTools.Error(...)
	end
end

LogLevel = {
    log = 5,
    logWarr = 4,
    logAss = 3,
    logErr = 2,
}

function CheckLogLevel(logLevel)
    if IsClient() then
        return true
    else
        return ServerLogTool:isLogEnabled(logLevel)
    end
end