---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/09/30 15:08
--- Describe: 行为树变量基类
---

---@class LuaBehav_RuntimeVariableBase : table
LuaBehav_RuntimeVariableBase = class(nil, "LuaBehav_RuntimeVariableBase")
function LuaBehav_RuntimeVariableBase:ctor(_data) end

---@public
---@param _configVariable LuaBehav_Define_TaskVariableConstruct 编辑器导出的节点的变量结构数据
---@param _variableDic table 树的变量字典
function LuaBehav_RuntimeVariableBase:Init(_configVariable, _variableDic)
	self.__type = _configVariable.variableType
	self.__value = _configVariable.variableValue
	self.__variableDic = _variableDic
end

---取变量值
---@public
function LuaBehav_RuntimeVariableBase:GetValue()
	--LogTools.LogByLevel(LogLevel.logErr, "LuaBehav_RuntimeVariableBase GetValue", "self.__type", self.__type, "self.__value", self.__value, "self.__variableDic", dumpTableEx(self.__variableDic))
	if self.__type == LuaBehav_Define_TaskVariableType.TreeSharedVariable then
		return self.__variableDic[self.__value]
	end
	
	return self.__value
end

---设置变量值
---@public
function LuaBehav_RuntimeVariableBase:SetValue(_value)
	if self.__type == LuaBehav_Define_TaskVariableType.TreeSharedVariable then
		self.__variableDic[self.__value] = _value
		return
	end
	
	self.__value = _value
end

---@public
function LuaBehav_RuntimeVariableBase:Clear()
	self.__type = nil
	self.__value = nil
	self.__variableDic = nil
end
return LuaBehav_RuntimeVariableBase