---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/15 14:30
--- Describe: 怪物进入巡逻状态
---

---@class LuaBehav_RuntimeTask_MonsPatrol : table
LuaBehav_RuntimeTask_MonsPatrol = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsPatrol")

function LuaBehav_RuntimeTask_MonsPatrol:OnStart()
	self:__OnStart()
	self.__callRet = LuaBehav_Interfaces.MonsPatrol(self.netId)
end

return LuaBehav_RuntimeTask_MonsPatrol