---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/08/23 14:49
--- Describe:
---

---@class LuaBehav_RuntimeTask_MonsRotateAxisLock : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_MonsRotateAxisLock = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsRotateAxisLock")

---@public
function LuaBehav_RuntimeTask_MonsRotateAxisLock:OnStart()
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.MonsRotateAxisLock(self.battleId, self.netId, self.configTask.lockType)
end

return LuaBehav_RuntimeTask_MonsRotateAxisLock