---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2023/02/23 14:49
--- Describe: 怪物清除最后一次受伤来源
---

---@class LuaBehav_RuntimeTask_MonsClearLastHurtFromTag : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_MonsClearLastHurtFromTag = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsClearLastHurtFromTag")

---@public
function LuaBehav_RuntimeTask_MonsClearLastHurtFromTag:OnStart()
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.MonsClearLastHurtFromTag(self.battleId, self.netId)
end

return LuaBehav_RuntimeTask_MonsClearLastHurtFromTag