---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/15 15:05
--- Describe: 怪物朝向当前目标
---

---@class LuaBehav_RuntimeTask_MonsFaceCurTarget : table
LuaBehav_RuntimeTask_MonsFaceCurTarget = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsFaceCurTarget")

function LuaBehav_RuntimeTask_MonsFaceCurTarget:OnStart()
	self:__OnStart()
	self.__callRet = LuaBehav_Interfaces.MonsFaceCurTarget(self.netId)
end

return LuaBehav_RuntimeTask_MonsFaceCurTarget