---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/03/21 11:33
--- Describe: 投放关卡单位
---

---@class LuaBehav_LevelDropUnitParam : table
LuaBehav_LevelDropUnitParam = class(nil, "LuaBehav_LevelDropUnitParam")
function LuaBehav_LevelDropUnitParam:ctor(_dropunitTask, _levelUnitId)
	self.dropType = _dropunitTask.dropType
	self.id = _levelUnitId
	self.firstCamp = _dropunitTask.firstCamp or LuaBehav_Define_BattleCampType.Monster
	self.secCamp = _dropunitTask.secondCamp or 1
	self.delayType = _dropunitTask.delayType or LuaBehav_Define_LevelDropUnitDelayType.None
	self.delayBottom = _dropunitTask.delayBottom or 0.1
	self.delayTop = _dropunitTask.delayTop or 1.5
end

---@class LuaBehav_RuntimeTask_LevelDropUnit : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_LevelDropUnit = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_LevelDropUnit")

---@private
function LuaBehav_RuntimeTask_LevelDropUnit:__InitConfigTaskVariables(_variableDic, _treeVariableDic)
	---@type LuaBehav_RuntimeVariableBase[]
	self.variables = {}
	if not _variableDic then
		self.variables.id = LuaBehav_RuntimeVariableBase.New()
		self.variables.id:Init({variableType = LuaBehav_Define_TaskVariableType.SampleVariable, variableValue = self.configTask.id}, _treeVariableDic)
	else
		for _key, _configVariable in pairs(_variableDic) do
			self.variables[_key] = LuaBehav_RuntimeVariableBase.New()
			self.variables[_key]:Init(_configVariable, _treeVariableDic)
		end
	end
end

function LuaBehav_RuntimeTask_LevelDropUnit:OnStart()
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.LevelDropUnit(self.battleId, LuaBehav_LevelDropUnitParam.New(self.configTask, self.variables.id:GetValue()))
end

return LuaBehav_RuntimeTask_LevelDropUnit