---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2021/12/24 17:07
--- Describe: 行为树打印节点
---

---@class LuaBehav_RuntimeTask_PrintLog : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_PrintLog = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_PrintLog")

-- 
function LuaBehav_RuntimeTask_PrintLog:OnStart()
	self:__OnStart()
	if CheckLogLevel(LogLevel.log) then
		LogTools.LogByLevel(LogLevel.log, "行为树打印节点", "CheckLuaBehav", self.configTask.log)
	end
end

return LuaBehav_RuntimeTask_PrintLog