---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/09/20 15:45
--- Describe: 检查当前身上buff层数
---

---@class LuaBehav_RuntimeTask_UnitCheckBuff : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_UnitCheckBuff = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_UnitCheckBuff")

function LuaBehav_RuntimeTask_UnitCheckBuff:IsConditionalTask()
	return true
end

function LuaBehav_RuntimeTask_UnitCheckBuff:OnUpdate(_deltaTime)
	local _retState = LuaBehav_Define_TaskState.Failure
	--LogTools.LogByLevel(LogLevel.logErr, "LuaBehav_RuntimeTask_UnitCheckBuff", "_getValue", _getValue, "self.configTask", dumpTableEx(self.configTask))

	local _isUnitBuff = self.configTask.isUnitBuff or false
	
	if not self.configTask.checkTarget or self.configTask.checkTarget == LuaBehav_Define_MonsCheckBuffTargetType.SelfUnit then
		local _getValue = LuaBehav_RuntimeTask_UnitCheckBuff.__GetBuffStackNum(self.battleId, self.netId, self.configTask.buffGroupId, _isUnitBuff)
		if self:__Check(self.configTask.compareValue, self.configTask.compareType, _getValue) then
			_retState = LuaBehav_Define_TaskState.Success
		end
	elseif self.configTask.checkTarget == LuaBehav_Define_MonsCheckBuffTargetType.CurTarget then
		local _unit = self.battleRoom.battleUnitManager:GetUnit(self.netId)
		if _unit then
			---@type BattleUnitCom_Behav
			local _behavCom = _unit:GetComponent(BattleUnitComponentType.Behav)
			if _behavCom then
				local _targetUnitNetId = _behavCom:GetTarget()
				local _getValue = LuaBehav_RuntimeTask_UnitCheckBuff.__GetBuffStackNum(self.battleId, _targetUnitNetId, self.configTask.buffGroupId, _isUnitBuff)
				if self:__Check(self.configTask.compareValue, self.configTask.compareType, _getValue) then
					_retState = LuaBehav_Define_TaskState.Success
				end
			end
		end
	elseif self.configTask.checkTarget == LuaBehav_Define_MonsCheckBuffTargetType.Subordination then
		local _unit = self.battleRoom.battleUnitManager:GetUnit(self.netId)
		if _unit then
			---@type BattleUnitCom_Subordination
			local _subordinationCom = _unit:GetComponent(BattleUnitComponentType.Subordination)
			if _subordinationCom then
				local _targetUnit = _subordinationCom:GetSubordinatedUnit()
				if _targetUnit then
					local _getValue = LuaBehav_RuntimeTask_UnitCheckBuff.__GetBuffStackNum(self.battleId, _targetUnit:GetNetId(), self.configTask.buffGroupId, _isUnitBuff)
					if self:__Check(self.configTask.compareValue, self.configTask.compareType, _getValue) then
						_retState = LuaBehav_Define_TaskState.Success
					end
				end
			end
		end 
	elseif self.configTask.checkTarget == LuaBehav_Define_MonsCheckBuffTargetType.AnyInSpecificCamps then
		for _, _camp in pairs(self.configTask.camps) do
			local _unitList = self.battleRoom.battleUnitManager:GetUnitListByCampType(_camp)
			for _, _targetUnit in pairs(_unitList) do
				local _getValue = LuaBehav_RuntimeTask_UnitCheckBuff.__GetBuffStackNum(self.battleId, _targetUnit:GetNetId(), self.configTask.buffGroupId, _isUnitBuff)
				if self:__Check(self.configTask.compareValue, self.configTask.compareType, _getValue) then
					_retState = LuaBehav_Define_TaskState.Success
					break
				end
			end
		end
	elseif self.configTask.checkTarget == LuaBehav_Define_MonsCheckBuffTargetType.AllInSpecificCamps then
		_retState = LuaBehav_Define_TaskState.Success
		for _, _camp in pairs(self.configTask.camps) do
			local _unitList = self.battleRoom.battleUnitManager:GetUnitListByCampType(_camp)
			for _, _targetUnit in pairs(_unitList) do
				local _getValue = LuaBehav_RuntimeTask_UnitCheckBuff.__GetBuffStackNum(self.battleId, _targetUnit:GetNetId(), self.configTask.buffGroupId, _isUnitBuff)
				if not self:__Check(self.configTask.compareValue, self.configTask.compareType, _getValue) then
					_retState = LuaBehav_Define_TaskState.Failure
					break
				end
			end
		end
	end
	
	self:__SetTaskState(_retState)
	return _retState
end

---@private
function LuaBehav_RuntimeTask_UnitCheckBuff:__Check(_compareValue, _compareType, _getValue)
	if _compareType == LuaBehav_Define_CompareType.Equal then
		return _getValue == _compareValue
	elseif _compareType == LuaBehav_Define_CompareType.UnEqual then
		return _getValue ~= _compareValue
	elseif _compareType == LuaBehav_Define_CompareType.Larger then
		return _getValue > _compareValue
	elseif _compareType == LuaBehav_Define_CompareType.Smaller then
		return _getValue < _compareValue
	elseif _compareType == LuaBehav_Define_CompareType.LargerEqual then
		return _getValue >= _compareValue
	elseif _compareType == LuaBehav_Define_CompareType.SmallerEqual then
		return _getValue <= _compareValue
	end
	return false
end

---@private
function LuaBehav_RuntimeTask_UnitCheckBuff.__GetBuffStackNum(_battleId, _netId, _buffGroupId, _isUnitBuff)
	local battleRoom = GetBattleRoom(_battleId)
	local _unit = battleRoom.battleUnitManager:GetUnit(_netId)
	if not _unit then
		return 0
	end

	if _isUnitBuff then
		---@type BattleUnitCom_Buff
		local _unitBuffCom = _unit:GetComponent(BattleUnitComponentType.Buff)
		if not _unitBuffCom then return 0 end
		local _unitBattleBuff = _unitBuffCom:GetBattleBuff(_buffGroupId)
		if not _unitBattleBuff then return 0 end
		return _unitBattleBuff.stackNum
	end
	
	
	local _obj = _unit:GetCurrentHeroObject()
	if not _obj then
		return 0
	end
	---@type BattleObjCom_Buff
	local _buffCom = _obj:GetComponent(BattleObjectComponentType.Buff)
	if not _buffCom then
		return 0
	end
	local _battleBuff = _buffCom:GetBattleBuff(_buffGroupId)
	if not _battleBuff then
		return 0
	end
	return _battleBuff.stackNum
end

return LuaBehav_RuntimeTask_UnitCheckBuff