---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/08/16 17:10
--- Describe: 朝指定方向移动一定时间，不按照路径决定朝向
---

---@class LuaBehav_MonsMoveTowards_2_Param : table
LuaBehav_MonsMoveTowards_2_Param = class(nil, "LuaBehav_MonsMoveTowards_2_Param")
function LuaBehav_MonsMoveTowards_2_Param:ctor(_netId, _configTask)
	self.netId = _netId
	self.posShift = Vector3.Clone(_configTask.posShift)
	self.faceTarget = _configTask.faceTarget
end


---@class LuaBehav_RuntimeTask_MonsMoveTowards_2 : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_MonsMoveTowards_2 = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsMoveTowards_2")

function LuaBehav_RuntimeTask_MonsMoveTowards_2:OnStart()
	--LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_MonsMoveTowards_2", "OnStart", "self.configTask", dumpTableEx(self.configTask))
	self:__OnStart()
	self.__timeTotal = self.configTask.time
	self.__startTime = self.battleRoom.behaviorManager:GetUnitTimeCnt()
	self.__listen = false
	self:RegistListenEvent(LuaBehav_Define_TaskListenEnum.MoveTowardsTwoEnd)
	self.__callRet = BEHAVIOR_ACTION.MonsMoveTowards_2(self.battleId, LuaBehav_MonsMoveTowards_2_Param.New(self.netId, self.configTask))
	--LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_MonsMoveTowards_2", "self.__callRet", self.__callRet)
end

function LuaBehav_RuntimeTask_MonsMoveTowards_2:OnListenEvent()
	--LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_MonsFaceCurTarget:OnListenEvent")
	self.__listen = true
end

function LuaBehav_RuntimeTask_MonsMoveTowards_2:OnUpdate(_deltaTime)
	if not self.__callRet then
		--LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_MonsMoveTowards_2 Call Failure")
		self:__SetTaskState(LuaBehav_Define_TaskState.Failure)
		return LuaBehav_Define_TaskState.Failure
	end
	
	local _netId = self.netId
	--监听到位置消息
	if self.__listen then
		self:__SetTaskState(LuaBehav_Define_TaskState.Success)
		BEHAVIOR_ACTION.MonsStopMoveTowards_2(self.battleId, _netId)
		--LogTools.LogByLevel(LogLevel.log, "checktime", "LuaBehav_RuntimeTask_MonsMoveTowards_2 xxxx receive end event")
		return LuaBehav_Define_TaskState.Success
	end

	local _timeDis = self.battleRoom.behaviorManager:GetUnitTimeCnt() - self.__startTime
	if _timeDis > self.__timeTotal then
		self:__SetTaskState(LuaBehav_Define_TaskState.Success)
		--LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_MonsMoveTowards_2 stop timeout")
		BEHAVIOR_ACTION.MonsStopMoveTowards_2(self.battleId, _netId)
		return LuaBehav_Define_TaskState.Success
	end
	
	self:__SetTaskState(LuaBehav_Define_TaskState.Running)
	return LuaBehav_Define_TaskState.Running
end

-- 节点被打断时调用
function LuaBehav_RuntimeTask_MonsMoveTowards_2:OnAbort()
	self:__OnAbort()
	self.__listen = false
	self:RemoveListenEvent(LuaBehav_Define_TaskListenEnum.MoveTowardsTwoEnd)
	BEHAVIOR_ACTION.MonsStopMoveTowards_2(self.battleId, self.netId)
end

-- 退出节点时调用
function LuaBehav_RuntimeTask_MonsMoveTowards_2:OnExit()
	self:__OnExit()
	self.__listen = false
	self:RemoveListenEvent(LuaBehav_Define_TaskListenEnum.MoveTowardsTwoEnd)
	--LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_MonsFaceCurTarget:OnExit")
end

return LuaBehav_RuntimeTask_MonsMoveTowards_2