---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/20 16:58
--- Describe: 事件监听节点
---

---@class LuaBehav_RuntimeTask_Event : table
LuaBehav_RuntimeTask_Event = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_Event")

function LuaBehav_RuntimeTask_Event:IsConditionalTask()
	return true
end

---@param _runtimeBehavTree LuaBehav_RuntimeBehavTree
function LuaBehav_RuntimeTask_Event:Init(_runtimeBehavTree, _taskIndex, _parentTaskIndex, _configTask, _cntInParent)
	self:__Init(_runtimeBehavTree, _taskIndex, _parentTaskIndex, _configTask, _cntInParent)
	self.useState = LuaBehav_Define_TaskState.Failure
	_runtimeBehavTree.runtimeBehavMgr:AddEventDic(LuaBehav_Define_EventTaskType.SpecificMonsOnHurt, self)
end

function LuaBehav_RuntimeTask_Event:OnUpdate(_deltaTime)
	self:__SetTaskState(self.useState)
	return self.useState
end

-- 
function LuaBehav_RuntimeTask_Event:OnEvent(_paramTab)
	local _taskType = self.configTask.eventType
	if _taskType == LuaBehav_Define_EventTaskType.SpecificMonsOnHurt then
		self:OnCaseSpecificMonsOnHurt(_paramTab)
	end
end

-- 
function LuaBehav_RuntimeTask_Event:OnCaseSpecificMonsOnHurt(_paramTab)
	local _netId = _paramTab.netId
	if _netId == self.netId then
		self.useState = LuaBehav_Define_TaskState.Success
		self.behavTree.runtimeBehavMgr:RemoveEventDic(self.configTask.eventType, self)
	end
end

return LuaBehav_RuntimeTask_Event