---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/04/02 17:05
--- Describe: 关卡触发器检查
---

---@class LuaBehav_LevelTriggerCheckParam : table
LuaBehav_LevelTriggerCheckParam = class(nil, "LuaBehav_LevelTriggerCheckParam")
function LuaBehav_LevelTriggerCheckParam:ctor(_configTask, _levelTriggerId)
	self.selectUnitType = _configTask.selectUnitType
	self.triggerId = _levelTriggerId
	self.targetIdList = _configTask.targetIdList
	self.checkInner = _configTask.checkInner
	self.needKeyTag = _configTask.needKeyTag  --是否需要是关键单位
end

------------------------------------------------------------------------------------------------------------------------
---@class LuaBehav_RuntimeTask_LevelTriggerChecker : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_LevelTriggerChecker = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_LevelTriggerChecker")

function LuaBehav_RuntimeTask_LevelTriggerChecker:IsConditionalTask()
	return true
end

-- 
function LuaBehav_RuntimeTask_LevelTriggerChecker:OnUpdate()
	if not self.__checkParam then
		local _triggerId
		if not self.variables or not self.variables.triggerId then
			_triggerId = self.configTask.triggerId
		else
			_triggerId = self.variables.triggerId:GetValue()
		end
		self.__checkParam = LuaBehav_LevelTriggerCheckParam.New(self.configTask, _triggerId)
	end
	local _retState = LuaBehav_Define_TaskState.Failure
	self.__callRet = BEHAVIOR_CHECK.LevelCheckLevelTrigger(self.battleId, self.__checkParam)
	--LogTools.LogByLevel(LogLevel.log, "LevelTrigger LuaBehav_RuntimeTask_LevelTriggerChecker", "self.__callRet", self.__callRet,"self.__checkParam", dumpTableEx(self.__checkParam))
	if self.__callRet then
		_retState = LuaBehav_Define_TaskState.Success
	end

	--LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_LevelTriggerChecker", "_retState", --LogTools.GetEnumTableDesc(LuaBehav_Define_TaskState, _retState))
	--_retState = LuaBehav_Define_TaskState.Success
	self:__SetTaskState(_retState)
	return _retState
end

function LuaBehav_RuntimeTask_LevelTriggerChecker:Clear()
	self:__Clear()
	self.__checkParam = nil
end
return LuaBehav_RuntimeTask_LevelTriggerChecker