---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/15 14:30
--- Describe: 怪物进入巡逻状态
---

---@class LuaBehav_MonsPatrolParam : table
LuaBehav_MonsPatrolParam = class(nil, "LuaBehav_LevelDropMonsParam")
function LuaBehav_MonsPatrolParam:ctor(_netId, _centerOnBorn)
	self.netId = _netId
	self.centerOnBorn = _centerOnBorn
end

---@class LuaBehav_RuntimeTask_MonsPatrol : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_MonsPatrol = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsPatrol")

function LuaBehav_RuntimeTask_MonsPatrol:OnStart()
	self:__OnStart()
	self.__timeTotal = self.configTask.timeTotal or 300
	self.__startTime = self.battleRoom.behaviorManager:GetUnitTimeCnt()
	if not self.__patrolParamData then
		local _centerOnBorn
		if self.variables.centerOnBorn then
			_centerOnBorn = self.variables.centerOnBorn:GetValue()
		else
			_centerOnBorn = self.configTask.centerOnBorn
		end
		self.__patrolParamData = LuaBehav_MonsPatrolParam.New(self.netId, _centerOnBorn)
	end
	
	self.__callRet = BEHAVIOR_ACTION.MonsPatrol(self.battleId, self.__patrolParamData)
end

function LuaBehav_RuntimeTask_MonsPatrol:OnUpdate(_deltaTime)
	if not self.__callRet then
		self:__SetTaskState(LuaBehav_Define_TaskState.Failure)
		return LuaBehav_Define_TaskState.Failure
	end
	
	local _timeDis = self.battleRoom.behaviorManager:GetUnitTimeCnt() - self.__startTime
	if _timeDis > self.__timeTotal then
		BEHAVIOR_ACTION.MonsPatrolEnd(self.battleId, self.netId)
		self:__SetTaskState(LuaBehav_Define_TaskState.Success)
		return LuaBehav_Define_TaskState.Success
	end
	
	self:__SetTaskState(LuaBehav_Define_TaskState.Running)
	return LuaBehav_Define_TaskState.Running
end

-- 节点被打断时调用
function LuaBehav_RuntimeTask_MonsPatrol:OnAbort()
	self:__OnAbort()
	BEHAVIOR_ACTION.MonsPatrolEnd(self.battleId, self.netId)
end

return LuaBehav_RuntimeTask_MonsPatrol