---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/08/02 16:34
--- Describe: 杀死指定关卡触发器中的单位
---

---@class LuaBehav_LevelKillUnitInTriggerParam : table
LuaBehav_LevelKillUnitInTriggerParam = class(nil, "LuaBehav_LevelKillUnitInTriggerParam")
function LuaBehav_LevelKillUnitInTriggerParam:ctor(_configTask)
	self.triggerId = _configTask.triggerId
	self.deadType = _configTask.deadType
	self.needKeyTag = _configTask.needKeyTag
	self.forceKiller = _configTask.forceKiller
end

---@class LuaBehav_RuntimeTask_LevelKillUnitInTrigger : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_LevelKillUnitInTrigger = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_LevelKillUnitInTrigger")

function LuaBehav_RuntimeTask_LevelKillUnitInTrigger:OnStart()
	----LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_LevelKillUnitInTrigger", "OnStart")
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.LevelKillUnitInTrigger(self.battleId, LuaBehav_LevelKillUnitInTriggerParam.New(self.configTask))
end


return LuaBehav_RuntimeTask_LevelKillUnitInTrigger