---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/11/18 11:35
--- Describe: 关卡标签操作
---

---@class LuaBehav_RuntimeTask_LevelTagOperate : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_LevelTagOperate = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_LevelTagOperate")

function LuaBehav_RuntimeTask_LevelTagOperate:OnStart()
	----LogTools.LogByLevel(LogLevel.log, "CheckLuaBehav", "LuaBehav_RuntimeTask_LevelTagOperate", "OnStart")
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.LevelTagOperate(self.battleId, self.configTask.tag, self.configTask.operType, self.configTask.value)
end

return LuaBehav_RuntimeTask_LevelTagOperate