---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/15 14:23
--- Describe: 怪物进入出生状态
---

---@class LuaBehav_RuntimeTask_MonsBorn : table
LuaBehav_RuntimeTask_MonsBorn = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsBorn")

function LuaBehav_RuntimeTask_MonsBorn:OnStart()
	self:__OnStart()
	self.__callRet = LuaBehav_Interfaces.MonsBorn(self.netId)
end

return LuaBehav_RuntimeTask_MonsBorn