---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2021/12/28 14:33
--- Describe: 等待(计时)节点
---

---@class LuaBehav_RuntimeTask_Wait : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_Wait = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_Wait")

function LuaBehav_RuntimeTask_Wait:OnStart()
	self:__OnStart()
	self.__startTime = self:GetCurTimeCnt()
	self.__totalTime = self.configTask.time
	if self.variables and self.variables.time then
		self.__totalTime = self.variables.time:GetValue()
	end
end

function LuaBehav_RuntimeTask_Wait:OnUpdate(_deltaTime)
	--LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_Wait:OnUpdate", "self:GetCurTimeCnt() - self.__startTime", self:GetCurTimeCnt() - self.__startTime, "self.configTask.time", self.configTask.time)
	local _state = LuaBehav_Define_TaskState.Running
	if self:GetCurTimeCnt() - self.__startTime > self.__totalTime then
		_state = LuaBehav_Define_TaskState.Success
	end
	self:SetTaskState(_state)
	return _state
end

return LuaBehav_RuntimeTask_Wait