---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/15 15:48
--- Describe: 怪物指定移动
---


---@class LuaBehav_MonsMoveTowardsParam : table
LuaBehav_MonsMoveTowardsParam = class(nil, "LuaBehav_LevelDropMonsParam")
function LuaBehav_MonsMoveTowardsParam:ctor(_netId, _configTask)
	self.netId = _netId
	self.spaceType = _configTask.spaceType
	self.posShift = Vector3.Clone(_configTask.posShift)
	self.stopWhenArrive = _configTask.stopWhenArrive
end

---@class LuaBehav_RuntimeTask_MonsMoveTowards : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_MonsMoveTowards = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsMoveTowards")

function LuaBehav_RuntimeTask_MonsMoveTowards:OnStart()
	----LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_MonsMoveTowards __OnMoveToPathPoint", "OnStart")
	self:__OnStart()
	self.__stopWhenArrive = self.configTask.stopWhenArrive
	self.__timeTotal = self.configTask.time
	self.__startTime = self.battleRoom.behaviorManager:GetUnitTimeCnt()
	self.__listen = false
	self:RegistListenEvent(LuaBehav_Define_TaskListenEnum.MoveTowardsEnd)
	self.__callRet = BEHAVIOR_ACTION.MonsMoveTowards(self.battleId, LuaBehav_MonsMoveTowardsParam.New(self.netId, self.configTask))
	----LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_MonsMoveTowards __OnMoveToPathPoint", "self.__callRet", self.__callRet)
end

function LuaBehav_RuntimeTask_MonsMoveTowards:OnListenEvent()
	self.__listen = true
end

function LuaBehav_RuntimeTask_MonsMoveTowards:OnUpdate(_deltaTime)
	if not self.__callRet then
		----LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_MonsMoveTowards xxxx __OnMoveToPathPoint Failure")
		self:__SetTaskState(LuaBehav_Define_TaskState.Failure)
		return LuaBehav_Define_TaskState.Failure
	end

	local _netId = self.netId
	--监听到位置消息
	if self.__stopWhenArrive and self.__listen then
		self:__SetTaskState(LuaBehav_Define_TaskState.Success)
		BEHAVIOR_ACTION.MonsStopMoveTowards(self.battleId, _netId)
		----LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_MonsMoveTowards xxxx __OnMoveToPathPoint stop receive event")
		return LuaBehav_Define_TaskState.Success
	end

	local _timeDis = self.battleRoom.behaviorManager:GetUnitTimeCnt() - self.__startTime
	if _timeDis > self.__timeTotal then
		self:__SetTaskState(LuaBehav_Define_TaskState.Success)
		BEHAVIOR_ACTION.MonsStopMoveTowards(self.battleId, _netId)
		----LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_MonsMoveTowards xxxx __OnMoveToPathPoint stop timeout")
		return LuaBehav_Define_TaskState.Success
	end
	
	self:__SetTaskState(LuaBehav_Define_TaskState.Running)
	return LuaBehav_Define_TaskState.Running
end

-- 节点被打断时调用
function LuaBehav_RuntimeTask_MonsMoveTowards:OnAbort()
	self:__OnAbort()
	self.__listen = false
	self:RemoveListenEvent(LuaBehav_Define_TaskListenEnum.MoveTowardsEnd)
	BEHAVIOR_ACTION.MonsStopMoveTowards(self.battleId, self.netId)
end

function LuaBehav_RuntimeTask_MonsMoveTowards:OnExit()
	----LogTools.LogByLevel(LogLevel.log, "LuaBehav_RuntimeTask_MonsMoveTowards xxxx __OnMoveToPathPoint OnExit")
	self:__OnExit()
	self.__listen = false
	self:RemoveListenEvent(LuaBehav_Define_TaskListenEnum.MoveTowardsEnd)
end

return LuaBehav_RuntimeTask_MonsMoveTowards