---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/04/25 15:14
--- Describe: 切换血量阶段（进入下一阶段, 按照策划的意思，没有跳过阶段）
---

---@class LuaBehav_RuntimeTask_MonsChangeStage : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_MonsChangeStage = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_MonsChangeStage")

function LuaBehav_RuntimeTask_MonsChangeStage:OnStart()
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.MonsChangeStage(self.battleId, self.netId)
end

return LuaBehav_RuntimeTask_MonsChangeStage