---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/06 14:43
--- Describe: 投放怪物节点（临时）
---

---@class LuaBehav_LevelDropMonsParam : table
LuaBehav_LevelDropMonsParam = class(nil, "LuaBehav_LevelDropMonsParam")
function LuaBehav_LevelDropMonsParam:ctor(_dicId, _firstCamp, _secCamp, _position, _rotation)
	self.dicId = _dicId
	self.firstCamp = _firstCamp or LuaBehav_Define_BattleCampType.Monster
	self.secCamp = _secCamp or 1
	self.position = _position or Vector3.zero_local()
	self.rotation = _rotation or Vector3.zero_local()
end


---@class LuaBehav_RuntimeTask_LevelDropMons : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_LevelDropMons = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_LevelDropMons")

function LuaBehav_RuntimeTask_LevelDropMons:OnStart()
	self:__OnStart()
	local _param = LuaBehav_LevelDropMonsParam.New(self.configTask.id, self.configTask.firstCamp, self.configTask.secondCamp, self.configTask.position, self.configTask.rotation)
	self.__callRet = BEHAVIOR_ACTION.LevelDropMons(self.battleId, _param)
end

return LuaBehav_RuntimeTask_LevelDropMons