---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/03/21 17:09
--- Describe: 关卡设置单位属性
---


---@class LuaBehav_LevelSetUnitPropertyParam : table
LuaBehav_LevelSetUnitPropertyParam = class(nil, "LuaBehav_LevelSetUnitPropertyParam")
function LuaBehav_LevelSetUnitPropertyParam:ctor(_setPropTask)
	self.targetType = _setPropTask.targetType
	self.idList = _setPropTask.idList
	self.propId = _setPropTask.propKey
	self.valueDescType = _setPropTask.valueDescType
	self.value = _setPropTask.value
end

---@class LuaBehav_RuntimeTask_LevelSetUnitProp : LuaBehav_RuntimeTask
LuaBehav_RuntimeTask_LevelSetUnitProp = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_LevelSetUnitProp")

function LuaBehav_RuntimeTask_LevelSetUnitProp:OnStart()
	self:__OnStart()
	self.__callRet = BEHAVIOR_ACTION.LevelSetUnitProp(self.battleId, LuaBehav_LevelSetUnitPropertyParam.New(self.configTask))
end

return LuaBehav_RuntimeTask_LevelSetUnitProp