---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2021/12/28 14:33
--- Describe: 等待(计时)节点
---

---@class LuaBehav_RuntimeTask_Wait : table
LuaBehav_RuntimeTask_Wait = class(LuaBehav_RuntimeTask, "LuaBehav_RuntimeTask_Wait")


function LuaBehav_RuntimeTask_Wait:OnStart()
	self:__OnStart()
	self.timeTotal = self.configTask.time
	self.timeAcc = 0
end

function LuaBehav_RuntimeTask_Wait:OnUpdate(_deltaTime)
	local _state = LuaBehav_Define_TaskState.Running
	local _curTime = self.timeAcc
	_curTime = _curTime + _deltaTime
	if _curTime > self.timeTotal then
		_state = LuaBehav_Define_TaskState.Success
	end
	self.timeAcc = _curTime
	self:SetTaskState(_state)
	LuaBehav_DebugTool.PrintTask("------------LuaBehav_RuntimeTask_Wait", "_curTime", _curTime)
	return _state
end

return LuaBehav_RuntimeTask_Wait