---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng
--- DateTime: 2023/06/19 11:05
--- Describe:
---

require "Battle/Logic/Room/BattleObject/BattleElement/ElementSource/ElementSource"
require "Battle/Logic/Room/BattleObject/BattleElement/ElementSource/ElementSource_Skill"

---@class ElementSourceType : table
ElementSourceType = {
    ---@type ElementSource
    None = ElementSource.New(0);
    ---@type ElementSource 主动技能
    ActiveSkill = ElementSource_Skill.New(1);
    ---@type ElementSource 被动技能
    TalentSkill = ElementSource.New(2);
    ---@type ElementSource Buff
    Buff = ElementSource.New(3);
}

-- 枚举映射
---@type ElementSource[] 枚举映射
local elementSourceTypeIdMap = {};

-- 初始化ElementSourceType映射
for _, value in pairs(ElementSourceType) do
    elementSourceTypeIdMap[tostring(value:GetId())] = value;
end

-- 根据id获取枚举
---@type function
---@param _id number
---@return ElementSource
function GetElementSourceTypeById(_id)
    local _elementType = elementSourceTypeIdMap[tostring(_id)]
    if not _elementType then
        return ElementSourceType.NONE
    end
    return _elementType
end

-- 获取元素枚举map
---@type function
---@return ElementSource[]
function GetElementSourceTypes()
    return elementSourceTypeIdMap
end