---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2022/1/19 17:15
--- 协议类

---@class ProtoCode:table 协议类
---@field id number 协议id
---@field type string 协议类型
---@field name string 协议名
---@field callBack function 协议回调
ProtoCode = class(nil,"ProtoCode")

---@public
---@param _id number 协议id
---@param _type number 协议类型
---@param _name string 协议名
---@param _callBack function 协议回调
---@param _isInitRoom function 是否是初始房间消息
function ProtoCode:ctor(_id,_type,_name,_callBack, _isInitRoom)
    self.id = _id;
    self.type = _type;
    self.name = _name;
    self.callBack = _callBack;
    self.isInitRoom = _isInitRoom;
end

---@public
---@return number 协议id
function ProtoCode:GetId()
    return self.id;
end

---@public
---@return number 协议类型
function ProtoCode:GetType()
    return self.type;
end

---@public
---@return string 协议名
function ProtoCode:GetName()
    return self.name;
end

function ProtoCode:IsInitRoomMsg()
    if self.isInitRoom == nil then
        return false
    end
    return self.isInitRoom;
end

---@public
---@param _message BattleRoomMessage
function ProtoCode:ApplyCallBack(_message)
    ---@type boolean
    local checkProto = SERVER_LIB and SERVER_LIB.performanceService:executeTimeCheck(PerformanceType.MESSAGE)
    if not checkProto then
        self.callBack(_message);
        return
    end

    -- 性能检测
    local _arriveNetIoTime = _message:GetArriveNetIoTime()
    local _arriveLuaTime = _message:GetArriveLuaTime()
    local _startDo = TimeUtils.nowExact()

    self.callBack(_message);

    if checkProto then
        SERVER_LIB.performanceService:checkLuaMsgExecuteTime(_message:GetId(), _message:GetUid(), _message:GetBattleId(),
                _arriveNetIoTime, _arriveLuaTime, _startDo, TimeUtils.nowExact(), _message:GetMessage())
    end
end