---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2022/1/10 17:24
--- 消息回调接口

-- 启动逻辑
function ProtoCallBack_StartBattleLogicTick()
    BATTLE_ROOM:StartLogicTick();
end

-- 玩家移动
---@param _message BattleRoomMessage 移动协议
function ProtoCallBack_PlayerMoveInput(_message)
    BATTLE_ROOM:OnPlayerMove(_message:GetUid(),_message:GetMessage().moveParam,_message:GetMessage().cameraParam);
end

-- 切换角色
---@param _message table
function ProtoCallBack_PlayerChangeLeader(_message)
    return BATTLE_ROOM:OnPlayerChangeLeader(_message);
end

-- 客户端logic_core接收每帧输出
---@param _message table
function ProtoCallBack_ClientReceiveOutputData(_message)

end