---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2022/1/5 16:16
--- 协议枚举

require "Battle/OutInterface/ProtoCode"
require "Battle/OutInterface/ProtoCallBackFunction"


PROTO_MESSAGE_TYPE = {
    InitRoom = 1,
    Room = 2,
    tick = 3,
    player = 4,
    logicOutput = 5,
    view = 6,
    broadcast = 7,
}

-- 消息枚举
---@type ProtoCode[] 协议映射
PROTO_CODE_ENUM = {
    --------------------------------------------------------------------------------------------------------------------
    ---战斗房间特殊消息
    --------------------------------------------------------------------------------------------------------------------
    ---@type ProtoCode 登录消息（分别发给远端逻辑核和本地逻辑核设置本地玩家id）
    BATTLE_LOGIN = ProtoCode.New(11003, PROTO_MESSAGE_TYPE.InitRoom, "msg.BattleLogin");
    ---@type ProtoCode 战斗开始，构建房间
    START_SOLO_BATTLE = ProtoCode.New(11028, PROTO_MESSAGE_TYPE.InitRoom, "msg.StartSoloBattle_S2C", nil, true);

    ---@type ProtoCode 爬塔开始
    ENTER_TOWER = ProtoCode.New(3600, PROTO_MESSAGE_TYPE.InitRoom, "msg.EnterTower_S2C", nil, true);
    ---@type ProtoCode 心跳消息
    BATTLE_HEART_BEAT = ProtoCode.New(11001, PROTO_MESSAGE_TYPE.tick, "msg.BattleHeartBeat");
    ---@type ProtoCode 心跳消息
    BATTLE_HEART_BEAT_S2C = ProtoCode.New(11002, PROTO_MESSAGE_TYPE.tick, "msg.BattleHeartBeat_S2C");
    --------------------------------------------------------------------------------------------------------------------
    ---@type ProtoCode 本地模式进入场景
    LOCAL_SCENE_PRE_ENTER = ProtoCode.New(11006, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleScenePreEnter_S2C");
    ---@type ProtoCode 本地模式进入场景
    LOCAL_SCENE_ENTER = ProtoCode.New(11007, PROTO_MESSAGE_TYPE.Room, "msg.BattleSceneEnter", ProtoCallBack_LocalSceneEnter);
    ---@type ProtoCode 本地模式进入场景
    LOCAL_SCENE_ENTER_S2C = ProtoCode.New(11008, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleSceneEnter_S2C");
    ---@type ProtoCode 本地模式离开副本
    LOCAL_BATTLE_LEAVE = ProtoCode.New(11019, PROTO_MESSAGE_TYPE.Room, "msg.BattleLeave", ProtoCallBack_LocalBattleLeave);
    ---@type ProtoCode 本地模式测试结束
    LOCAL_TEST_BATTLE_OVER = ProtoCode.New(11021, PROTO_MESSAGE_TYPE.Room, "msg.TestBattleOver", ProtoCallBack_LocalTestBattleOver);
    --------------------------------------------------------------------------------------------------------------------
    ---@type ProtoCode 创建玩家
    CREATE_PLAYER_UNIT_L2S = ProtoCode.New(13000, PROTO_MESSAGE_TYPE.Room, "msg.CreatePlayerUnitL2S");
    ---@type ProtoCode 创建怪物
    CREATE_MONSTER_UNIT_L2S = ProtoCode.New(13001, PROTO_MESSAGE_TYPE.Room, "msg.CreateMonsterUnitL2S");
    ---@type ProtoCode 寻路请求
    UNIT_PATH_FIND_REQUEST = ProtoCode.New(13002, PROTO_MESSAGE_TYPE.Room, "msg.PathFindRequest");
    ---@type ProtoCode 寻路停止
    UNIT_PATH_FIND_CANCEL = ProtoCode.New(13003, PROTO_MESSAGE_TYPE.Room, "msg.PathFindRequestCancel");
    ---@type ProtoCode 寻路请求返回
    FIND_PATH_BACK = ProtoCode.New(13004, PROTO_MESSAGE_TYPE.Room, "msg.PathFindResult", ProtoCallBack_PathFindResult);
    ---@type ProtoCode 通知显示层切换英雄
    PLAYER_CHANGE_LEADER_L2S = ProtoCode.New(13005, PROTO_MESSAGE_TYPE.Room, "msg.PlayerChangeLeaderL2S");
    ---@type ProtoCode 通知显示层战斗单位受伤/治疗
    UNIT_HURT_L2S = ProtoCode.New(13006, PROTO_MESSAGE_TYPE.Room, "msg.UnitHurtL2S");
    -----@type ProtoCode 通知显示层战斗单位受到治疗
    --UNIT_CURE_L2S = ProtoCode.New(13007, PROTO_MESSAGE_TYPE.Room, "msg.UnitCureL2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 战斗演出(通用)
    BATTLE_PLAY_ACT_L2S = ProtoCode.New(13008, PROTO_MESSAGE_TYPE.view, "msg.BattlePlayAct_L2S");
    ---@type ProtoCode 客户端View -> 客户端Logic 战斗演出(通用)
    BATTLE_PLAY_ACT_END_S2L = ProtoCode.New(13009, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattlePlayActEnd_S2L", ProtoCallBack_BattlePlayActEnd_S2L);
    ---@type ProtoCode 客户端Logic -> 客户端View 战斗剧情(通用)
    BATTLE_PLAY_PLOT_L2S = ProtoCode.New(13010, PROTO_MESSAGE_TYPE.view, "msg.BattlePlayPlot_L2S");
    ---@type ProtoCode 客户端View -> 客户端Logic 战斗剧情(通用)
    BATTLE_PLAY_PLOT_END_S2L = ProtoCode.New(13011, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattlePlayPlotEnd_S2L", ProtoCallBack_BattlePlayPlotEnd_S2L);
    ---@type ProtoCode 客户端Logic -> 客户端View 战斗UI(通用)
    BATTLE_PLAY_UI_L2S = ProtoCode.New(13012, PROTO_MESSAGE_TYPE.view, "msg.BattlePlayUi_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 显示战斗操作UI
    BATTLE_SHOW_RUN_UI_L2S = ProtoCode.New(13013, PROTO_MESSAGE_TYPE.view, "msg.BattleShowRunUi_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 显示战斗结束UI
    BATTLE_OVER_L2V = ProtoCode.New(13014, PROTO_MESSAGE_TYPE.view, "msg.BattleOver_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 拾取掉落物
    PICK_UP_FALL_OBJECT_L2S = ProtoCode.New(13015, PROTO_MESSAGE_TYPE.view, "msg.PickUpFallObject_L2S");
    ---@type ProtoCode 客户端View -> 客户端Logic 拾取掉落物
    PICK_UP_FALL_OBJECT_S2L = ProtoCode.New(13016, PROTO_MESSAGE_TYPE.logicOutput, "msg.PickUpFallObject_S2L", ProtoCallBack_PickUpFallObject_S2L);
    ---@type ProtoCode 客户端Logic -> 客户端View 掉落
    DROP_FALL_OBJECT_L2S = ProtoCode.New(13017, PROTO_MESSAGE_TYPE.view, "msg.DropFallObject_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 元素反应
    ELEMENT_REACT_L2S = ProtoCode.New(13018, PROTO_MESSAGE_TYPE.view, "msg.ElementReact_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 元素附着
    ELEMENT_ATTACH_L2S = ProtoCode.New(13019, PROTO_MESSAGE_TYPE.view, "msg.ElementAttach_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 元素移除
    ELEMENT_REMOVE_L2S = ProtoCode.New(13020, PROTO_MESSAGE_TYPE.view, "msg.ElementRemove_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 元素衰减警告
    ELEMENT_REDUCE_WARNING_L2S = ProtoCode.New(13021, PROTO_MESSAGE_TYPE.view, "msg.ElementReduceWarning_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端 关闭逻辑核
    BATTLE_LOGIC_CLOSE_L2S = ProtoCode.New(13022, PROTO_MESSAGE_TYPE.view, "msg.BattleLogicClose_L2S");
    ---@type ProtoCode 创建发射器
    CREATE_EMITTER_L2S = ProtoCode.New(13023, PROTO_MESSAGE_TYPE.view, "msg.CreateEmitter_L2S");
    ---@type ProtoCode 销毁发射器
    DESTROY_EMITTER_L2S = ProtoCode.New(13024, PROTO_MESSAGE_TYPE.view, "msg.DestroyEmitter_L2S");
    ---@type ProtoCode 停止发射器
    STOP_EMITTER_L2S = ProtoCode.New(13025, PROTO_MESSAGE_TYPE.view, "msg.StopEmitter_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 产生闪电球（电磁反应）
    CREATE_ELEMENT_LIGHTNING_BALL_L2S = ProtoCode.New(13026, PROTO_MESSAGE_TYPE.view, "msg.CreateElementLightningBall_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 打开高能预警
    OPEN_WARNING_UI_L2S = ProtoCode.New(13027, PROTO_MESSAGE_TYPE.view, "msg.OpenWarningUI_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 同步战斗单位状态到显示层
    BATTLE_UNIT_STATE_CHANGE_L2S = ProtoCode.New(13028, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitStateChange_L2S");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层
    SERVER_BATTLE_PLAY_ACT_END_L2V = ProtoCode.New(13029, PROTO_MESSAGE_TYPE.view, "msg.ServerBattlePlayActEnd_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层
    SERVER_BATTLE_PLAY_PLOT_END_L2V = ProtoCode.New(13030, PROTO_MESSAGE_TYPE.view, "msg.ServerBattlePlayPlotEnd_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层 单位死亡
    UNIT_DEAD_L2V = ProtoCode.New(13031, PROTO_MESSAGE_TYPE.view, "msg.UnitDead_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 单位属性改变
    BATTLE_UNIT_PROP_CHANGE_L2V = ProtoCode.New(13032, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitPropChange_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层战斗单位技能数据
    BATTLE_UNIT_SKILL_DATA_L2V = ProtoCode.New(13033, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitSkillData_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层战斗单位buff数据
    BATTLE_UNIT_BUFF_DATA_L2V = ProtoCode.New(13034, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitBuffData_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层战斗单位技能cd
    BATTLE_UNIT_SKILL_COOL_DOWN_DATA_L2V = ProtoCode.New(13035, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitSkillCoolDownData_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 通知显示层打开战斗内通讯
    OPEN_BATTLE_COMMUNICATION_L2V = ProtoCode.New(13036, PROTO_MESSAGE_TYPE.view, "msg.OpenBattleCommunicationUI_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层登录消息
    BATTLE_LOGIN_L2V = ProtoCode.New(13037, PROTO_MESSAGE_TYPE.view, "msg.BattleLogin_L2V");
    ---@type ProtoCode 武装进入过载(CL->View)
    WEAPON_ENTER_OVER_LOAD_L2V = ProtoCode.New(13038, PROTO_MESSAGE_TYPE.view, "msg.WeaponEnterOverLoad_L2V");
    ---@type ProtoCode 武装退出过载(CL->View)
    WEAPON_EXIT_OVER_LOAD_L2V = ProtoCode.New(13039, PROTO_MESSAGE_TYPE.view, "msg.WeaponExitOverLoad_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层创建战场触发器
    CREATE_LEVEL_TRIGGER_L2V = ProtoCode.New(13040, PROTO_MESSAGE_TYPE.view, "msg.CreateLevelTrigger_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层删除战场触发器
    REMOVE_LEVEL_TRIGGER_L2V = ProtoCode.New(13041, PROTO_MESSAGE_TYPE.view, "msg.RemoveLevelTrigger_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层切换血量阶段
    UNIT_CHANGE_STAGE_L2V = ProtoCode.New(13042, PROTO_MESSAGE_TYPE.view, "msg.UnitChangeStage_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层触发弹幕事件
    BARRAGE_TRIG_EVENT_L2V = ProtoCode.New(13043, PROTO_MESSAGE_TYPE.view, "msg.BarrageTrigEvent_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层创建区域
    CREATE_AREA_TRIG_L2V = ProtoCode.New(13044, PROTO_MESSAGE_TYPE.view, "msg.CreateAreaTrig_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层开启区域
    OPEN_AREA_TRIG_L2V = ProtoCode.New(13045, PROTO_MESSAGE_TYPE.view, "msg.OpenAreaTrig_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层关闭区域
    CLOSE_AREA_TRIG_L2V = ProtoCode.New(13046, PROTO_MESSAGE_TYPE.view, "msg.CloseAreaTrig_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知显示层销毁区域
    DESTROY_AREA_TRIG_L2V = ProtoCode.New(13047, PROTO_MESSAGE_TYPE.view, "msg.DestroyAreaTrig_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知object死亡
    UNIT_OBJECT_DEAD_L2V = ProtoCode.New(13048, PROTO_MESSAGE_TYPE.view, "msg.UnitObjectDead_L2V");
    ---@type ProtoCode 转向目标
    TURN_TO_TARGET_L2V = ProtoCode.New(13049, PROTO_MESSAGE_TYPE.view, "msg.TurnToTarget_V2L",ProtoCallBack_TurnToTarget);
    ---@type ProtoCode 客户端Logic -> 客户端显示层 通知触发战斗内新手引导
    TRIG_BATTLE_GUIDE_L2V = ProtoCode.New(13050, PROTO_MESSAGE_TYPE.view, "msg.TrigBattleGuide_L2V");
    ---@type ProtoCode 关卡触发新手引导UI操作 客户端Logic -> 客户端显示层
    LEVEL_TRIG_UI_OPERATE_L2V = ProtoCode.New(13051, PROTO_MESSAGE_TYPE.view, "msg.LevelTrigUIOperate_L2V");
    ---@type ProtoCode 关卡触发玩家控制器操作 客户端Logic -> 客户端显示层
    LEVEL_TRIG_CONTROLLER_OPERATE_L2V = ProtoCode.New(13052, PROTO_MESSAGE_TYPE.view, "msg.LevelTrigControllerOperate_L2V");
    ---@type ProtoCode 创建场景物件 客户端Logic -> 客户端显示层
    GENERATE_SCENE_OBJ_L2V = ProtoCode.New(13053, PROTO_MESSAGE_TYPE.view, "msg.CreateSceneObj_L2V");
    ---@type ProtoCode 移除场景物件 客户端Logic -> 客户端显示层
    REMOVE_SCENE_OBJ_L2V = ProtoCode.New(13054, PROTO_MESSAGE_TYPE.view, "msg.RemoveSceneObj_L2V");
    ---@type ProtoCode 切换场景物件状态 客户端Logic -> 客户端显示层
    CHANGE_SCENE_OBJ_STATE_L2V = ProtoCode.New(13055, PROTO_MESSAGE_TYPE.view, "msg.ChangeSceneObjState_L2V");
    ---@type ProtoCode 切换战斗BGM 客户端Logic -> 客户端显示层
    CHANGE_BATTLE_BGM_L2V = ProtoCode.New(13056, PROTO_MESSAGE_TYPE.view, "msg.ChangeBattleBGM_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 取消元素衰减警告
    ELEMENT_CANCEL_REDUCE_WARNING_L2V = ProtoCode.New(13057, PROTO_MESSAGE_TYPE.view, "msg.ElementCancelReduceWarning_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 产生冰风球（冰风反应）
    CREATE_ELEMENT_ICE_WIND_BALL_L2V = ProtoCode.New(13058, PROTO_MESSAGE_TYPE.view, "msg.CreateElementIceWindBall_L2V");
    ---@type ProtoCode 创建区域
    CREATE_AREA_TRIGGER_UNIT_L2V = ProtoCode.New(13059, PROTO_MESSAGE_TYPE.view, "msg.CreateAreaTriggerUnitL2V");
    ---@type ProtoCode 创建召唤物
    CREATE_SUMMONED_MONS_UNIT_L2V = ProtoCode.New(13060, PROTO_MESSAGE_TYPE.view, "msg.CreateSummonedMonsUnitL2V");
    ---@type ProtoCode 推送三星列表
    GET_MAIN_LEVEL_STAR_LIST_L2V = ProtoCode.New(13061, PROTO_MESSAGE_TYPE.view, "msg.GetMainLevelStarList_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 单位buff触发
    BATTLE_OBJECT_BUFF_TRIGGER_L2V = ProtoCode.New(13062, PROTO_MESSAGE_TYPE.view, "msg.BattleObjectBuffTrigger_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 创建目标点
    CREATE_TARGET_POINT_L2V = ProtoCode.New(13063, PROTO_MESSAGE_TYPE.view, "msg.CreateTargetPointUnitL2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 关卡目标数据
    LEVEL_TARGET_L2V = ProtoCode.New(13064, PROTO_MESSAGE_TYPE.view, "msg.LevelTarget_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 单位目标改变
    UNIT_TARGET_CHANGE_L2V = ProtoCode.New(13065, PROTO_MESSAGE_TYPE.view, "msg.UnitTargetChange_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 创建护罩
    CREATE_SHIELD_L2V = ProtoCode.New(13066, PROTO_MESSAGE_TYPE.view, "msg.CreateShieldUnitL2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 模式切换
    BATTLE_OBJECT_CHANGE_AIM_MODE_L2V = ProtoCode.New(13067, PROTO_MESSAGE_TYPE.view, "msg.BattleObjectChangeAimMode_L2V");
    ---@type ProtoCode 客户端Logic -> 客户端View 生命周期重置
    BATTLE_OBJECT_LIFE_RESET_L2V = ProtoCode.New(13068, PROTO_MESSAGE_TYPE.view, "msg.BattleObjectLifeReset_L2V");
    ---@type ProtoCode 客户端View -> 客户端Logic 客户端通知开始播放timeline
    CLIENT_START_TIME_LINE_V2L = ProtoCode.New(13069, PROTO_MESSAGE_TYPE.logicOutput, "msg.ClientStartTimeline_V2L", ProtoCallBack_ClientStartTimeline);
    ---@type ProtoCode 客户端View -> 客户端Logic 生命周期重置
    CLIENT_STOP_TIME_LINE_V2L = ProtoCode.New(13070, PROTO_MESSAGE_TYPE.logicOutput, "msg.ClientStopTimeline_V2L", ProtoCallBack_ClientStopTimeline);
    ---@type ProtoCode 瞄准的目标
    AIM_TARGET_V2L = ProtoCode.New(13071, PROTO_MESSAGE_TYPE.player, "msg.AimTarget_V2L", ProtoCallBack_AimTargetV2L);
    ---@type ProtoCode 消弹消息
    DESTROY_BULLET_V2L = ProtoCode.New(13072, PROTO_MESSAGE_TYPE.logicOutput, "msg.DestroyBullet_V2L", ProtoCallBack_DestroyBullet_V2L);
    ---@type ProtoCode 消弹消息
    SYNC_LEVEL_PAUSE_TIME_L2V = ProtoCode.New(13073, PROTO_MESSAGE_TYPE.view, "msg.SyncLevelPauseTime_L2V");
    ---@type ProtoCode 开启分块
    UNIT_OPEN_BLOCK_L2V = ProtoCode.New(13074, PROTO_MESSAGE_TYPE.view, "msg.UnitOpenBlock_L2V");
    ---@type ProtoCode 关闭分块
    UNIT_CLOSE_BLOCK_L2V = ProtoCode.New(13075, PROTO_MESSAGE_TYPE.view, "msg.UnitCloseBlock_L2V");
    ---@type ProtoCode 开启弱点
    UNIT_OPEN_WEAKNESS_L2V = ProtoCode.New(13076, PROTO_MESSAGE_TYPE.view, "msg.UnitOpenWeakness_L2V");
    ---@type ProtoCode 关闭弱点
    UNIT_CLOSE_WEAKNESS_L2V = ProtoCode.New(13077, PROTO_MESSAGE_TYPE.view, "msg.UnitCloseWeakness_L2V");
    ---@type ProtoCode 弱点血量变化
    UNIT_WEAKNESS_HP_CHANGE_L2V = ProtoCode.New(13078, PROTO_MESSAGE_TYPE.view, "msg.UnitWeaknessHpChange_L2V");
    ---@type ProtoCode 单位交互结果
    UNIT_HANDLE_RESULT_L2V = ProtoCode.New(13079, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitHandleResult_L2V");
    ---@type ProtoCode 单位交互状态变化
    UNIT_HANDLE_STATE_CHANGE_L2V = ProtoCode.New(13080, PROTO_MESSAGE_TYPE.view, "msg.BattleUnitHandleStateChange_L2V");
    ---@type ProtoCode 关卡触发一般UI操作 客户端Logic -> 客户端显示层
    LEVEL_TRIG_NORMAL_UI_OPERATE_L2V = ProtoCode.New(13081, PROTO_MESSAGE_TYPE.view, "msg.LevelTrigNormalUIOperate_L2V");
    ---@type ProtoCode 关卡Tag值改变 客户端Logic -> 客户端显示层
    CHANGE_TAG_L2V = ProtoCode.New(13082, PROTO_MESSAGE_TYPE.view, "msg.ChangeTag_L2V");
    ---@type ProtoCode 钻环玩法中玩家金币积分变化 客户端Logic -> 客户端显示层
    COLLECTOR_COIN_POINTS_CHANGE_L2V = ProtoCode.New(13083, PROTO_MESSAGE_TYPE.view, "msg.CollectorCoinPointsChange_L2V");
    ---@type ProtoCode 换弹开始 客户端Logic -> 客户端显示层
    RELOAD_BULLET_START_L2V = ProtoCode.New(13084, PROTO_MESSAGE_TYPE.view, "msg.ReloadBulletStart_L2V");
    ---@type ProtoCode 玩家离开 客户端Logic -> 客户端显示层
    PLAYER_LEAVE_L2V = ProtoCode.New(13085, PROTO_MESSAGE_TYPE.view, "msg.PlayerLeave_L2V");
    ---@type ProtoCode 玩家进入 客户端Logic -> 客户端显示层
    PLAYER_ENTER_L2V = ProtoCode.New(13086, PROTO_MESSAGE_TYPE.view, "msg.PlayerEnter_L2V");
    ---@type ProtoCode 重连 客户端Logic -> 客户端显示层
    PLAYER_RECONNECT_BATTLE_ROOM_INFO_L2V = ProtoCode.New(13087, PROTO_MESSAGE_TYPE.view, "msg.PlayerReconnectBattleRoomInfo_L2V");
    ---@type ProtoCode 换弹开始 客户端Logic -> 客户端显示层
    RELOAD_BULLET_END_L2V = ProtoCode.New(13088, PROTO_MESSAGE_TYPE.view, "msg.ReloadBulletEnd_L2V");
    ---@type ProtoCode 换弹开始 客户端Logic -> 客户端显示层
    LEVEL_CHANGE_TIME_LIMIT_L2V = ProtoCode.New(13089, PROTO_MESSAGE_TYPE.view, "msg.LevelChangeTimeLimit_L2V");
    ---@type ProtoCode 修改勇士状态 客户端Logic -> 客户端显示层
    UNIT_CHANGE_WARRIOR_STATE_L2V = ProtoCode.New(13090, PROTO_MESSAGE_TYPE.view, "msg.UnitChangeWarriorState_L2V");
    ---@type ProtoCode 开始朝向目标 客户端Logic -> 客户端显示层
    UNIT_START_FACE_TARGET_L2V = ProtoCode.New(13091, PROTO_MESSAGE_TYPE.view, "msg.StartFaceTarget_L2V");
    ---@type ProtoCode 结束朝向目标 客户端Logic -> 客户端显示层
    UNIT_STOP_FACE_TARGET_L2V = ProtoCode.New(13092, PROTO_MESSAGE_TYPE.view, "msg.StopFaceTarget_L2V");
    ---@type ProtoCode 行为树状态
    PUSH_BEHAV_INFO_L2V = ProtoCode.New(13093, PROTO_MESSAGE_TYPE.player, "msg.PushBehaviorInfo");
    ---@type ProtoCode 隐藏分块
    UNIT_HIDE_BLOCK_V2L = ProtoCode.New(13094, PROTO_MESSAGE_TYPE.view, "msg.UnitHideBlock_L2V");
    ---@type ProtoCode 隐藏分块结束
    UNIT_HIDE_BLOCK_END_V2L = ProtoCode.New(13095, PROTO_MESSAGE_TYPE.view, "msg.UnitHideBlockEnd_L2V");
    ---@type ProtoCode 隐藏分块网格
    UNIT_HIDE_BLOCK_MESH_V2L = ProtoCode.New(13096, PROTO_MESSAGE_TYPE.view, "msg.UnitHideBlockMesh_L2V");
    ---@type ProtoCode 隐藏分块网格结束
    UNIT_HIDE_BLOCK_MESH_END_V2L = ProtoCode.New(13097, PROTO_MESSAGE_TYPE.view, "msg.UnitHideBlockMeshEnd_L2V");
    ---@type ProtoCode 弱点击破
    WEAKNESS_BROKEN_V2L = ProtoCode.New(13098, PROTO_MESSAGE_TYPE.view, "msg.WeaknessBroken_L2V");
    ---@type ProtoCode 通知切换阶段
    NOTIFY_CHANGE_BATTLE_LEVEL_STAGE_L2V = ProtoCode.New(13099, PROTO_MESSAGE_TYPE.view, "msg.NotifyChangeBattleLevelStage_L2V");
    ---@type ProtoCode 元素值改变
    ELEMENT_VALUE_CHANGE_L2V = ProtoCode.New(13100, PROTO_MESSAGE_TYPE.view, "msg.ElementValueChange_L2V");
    ---@type ProtoCode 采集金币次数改变
    COLLECTOR_COIN_NUM_CHANGE_L2V = ProtoCode.New(13101, PROTO_MESSAGE_TYPE.view, "msg.CollectorCoinNumChange_L2V");
    ---@type ProtoCode 肉鸽主公技开启状态变化
    ROGUE_UNIT_SKILL_OPENED_CHANGE_L2V = ProtoCode.New(13102, PROTO_MESSAGE_TYPE.view, "msg.RogueUnitSkillOpenedChange_L2V");
    ---@type ProtoCode unit覆盖护罩变化
    UNIT_COVER_SHIELD_CHANGE_L2V = ProtoCode.New(13103, PROTO_MESSAGE_TYPE.view, "msg.UnitCoverShieldChange_L2V");
    ---@type ProtoCode 通知显示层开始切换血量阶段
    UNIT_START_CHANGE_STAGE_L2V = ProtoCode.New(13105, PROTO_MESSAGE_TYPE.view, "msg.UnitStartChangeStage_L2V");
    ---@type ProtoCode 战斗gm
    EDITOR_GM_TOOLS_V2L = ProtoCode.New(13999, PROTO_MESSAGE_TYPE.player, "msg.EditorGMTools_V2L", ProtoCallBack_PlayerGM);
    --------------------------------------------------------------------------------------------------------------------

    ---@type ProtoCode 开始战斗
    BATTLE_LUA_EVENT_PUSH = ProtoCode.New(12002, PROTO_MESSAGE_TYPE.broadcast, "msg.BattleLuaEvent_Push", ProtoCallBack_BattleEventPush);
    ---@type ProtoCode 玩家换人输入
    PLAYER_CHANGE_LEADER_INPUT = ProtoCode.New(12005, PROTO_MESSAGE_TYPE.player, "msg.PlayerChangeLeaderInput", ProtoCallBack_PlayerChangeLeaderInput);
    ---@type ProtoCode 进入下一关卡阶段
    GO_TO_NEXT_BATTLE_LEVEL_STAGE = ProtoCode.New(12008, PROTO_MESSAGE_TYPE.Room, "msg.GotoNextBattleLevelStage", ProtoCallBack_GotoNextBattleLevelStage);
    ---@type ProtoCode 通知切换阶段
    NOTIFY_CHANGE_BATTLE_LEVEL_STAGE = ProtoCode.New(12009, PROTO_MESSAGE_TYPE.broadcast, "msg.NotifyChangeBattleLevelStage", ProtoCallBack_NotifyChangeBattleLevelStage);
    ---@type ProtoCode 玩家换人服务器广播
    PLAYER_CHANGE_LEADER_S2C = ProtoCode.New(12010, PROTO_MESSAGE_TYPE.broadcast, "msg.PlayerChangeLeader_S2C", ProtoCallBack_PlayerChangeLeaderS2C);
    ---@type ProtoCode 战斗单位受伤输入
    --UNIT_HURT_INPUT = ProtoCode.New(12012, PROTO_MESSAGE_TYPE.Room, "msg.UnitHurtInput", ProtoCallBack_UnitHurtInput);
    -----@type ProtoCode 战斗单位治疗输入
    --UNIT_CURE_INPUT = ProtoCode.New(12013, PROTO_MESSAGE_TYPE.Room, "msg.UnitCureInput", ProtoCallBack_UnitCureInput);
    ---@type ProtoCode 战斗单位受伤广播
    UNIT_HURT_BROAD_CAST = ProtoCode.New(12014, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitHurt_S2C", ProtoCallBack_UnitHurt_S2C);
    ---@type ProtoCode 战斗单位治疗广播
    --UNIT_CURE_BROAD_CAST = ProtoCode.New(12015, PROTO_MESSAGE_TYPE.Room, "msg.UnitCure_S2C", ProtoCallBack_UnitCure_S2C);
    ---@type ProtoCode 战斗单位巡逻广播
    UNIT_PATROL_S2C = ProtoCode.New(12016, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitPatrol_S2C", ProtoCallBack_UnitPatrol_S2C);
    ---@type ProtoCode 战斗单位取消巡逻广播
    UNIT_PATROL_CANCEL_S2C = ProtoCode.New(12017, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitPatrolCancel_S2C", ProtoCallBack_UnitPatrolCancel_S2C);
    -----@type ProtoCode 怪物移动
    --MONSTER_MOVE_INPUT = ProtoCode.New(12018, PROTO_MESSAGE_TYPE.Room, "msg.MonsterMoveInput", ProtoCallBack_MonsterPathFindList);
    ---@type ProtoCode 服务器同步路点给所有客户端
    MONSTER_SYNC_PATH_POINT_LIST_S2C = ProtoCode.New(12019, PROTO_MESSAGE_TYPE.broadcast, "msg.MonsterSyncPathPointList_S2C", ProtoCallBack_MonsterSyncPathPointListS2C);
    ---@type ProtoCode 服务端Logic -> 客户端Logic 战斗演出(通用)
    BATTLE_PLAY_ACT_S2C = ProtoCode.New(12021, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattlePlayAct_S2C", ProtoCallBack_BattlePlayAct_S2C);
    ---@type ProtoCode 客户端Logic -> 服务端Logic 战斗演出结束(通用)
    BATTLE_PLAY_ACT_END = ProtoCode.New(12022, PROTO_MESSAGE_TYPE.Room, "msg.BattlePlayActEnd", ProtoCallBack_BattlePlayActEnd);
    ---@type ProtoCode 服务端Logic -> 客户端Logic 战斗剧情(通用)
    BATTLE_PLAY_PLOT_S2C = ProtoCode.New(12023, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattlePlayPlot_S2C", ProtoCallBack_BattlePlayPlot_S2C);
    ---@type ProtoCode 客户端Logic -> 服务端Logic 战斗剧情结束(通用)
    BATTLE_PLAY_PLOT_END = ProtoCode.New(12024, PROTO_MESSAGE_TYPE.Room, "msg.BattlePlayPlotEnd", ProtoCallBack_BattlePlayPlotEnd);
    ---@type ProtoCode 服务端Logic -> 客户端Logic 战斗UI(通用)
    BATTLE_PLAY_UI_S2C = ProtoCode.New(12025, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattlePlayUi_S2C", ProtoCallBack_BattlePlayUi_S2C);
    ---@type ProtoCode 战斗服通知战斗结束
    NOTIFY_BATTLE_OVER_RESULT_PUSH = ProtoCode.New(12026, PROTO_MESSAGE_TYPE.broadcast, "msg.NotifyBattleOverResult_Push", ProtoCallBack_NotifyBattleOverResult);
    ---@type ProtoCode 推送战斗结算数据
    BATTLE_OVER = ProtoCode.New(12027, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleOver", ProtoCallBack_BattleOver);
    ---@type ProtoCode  推送战斗结算数据
    BATTLE_OVER_PUSH = ProtoCode.New(12028, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleOver_Push", ProtoCallBack_BattleOver_Push);
    ---@type ProtoCode 玩家输入技能按钮
    PLAYER_PRESS_KEY = ProtoCode.New(12029, PROTO_MESSAGE_TYPE.player, "msg.PlayerPressKey", ProtoCallBack_PlayerPressKey);
    ---@type ProtoCode 战斗单位开始追逐目标广播
    UNIT_CHASE_TARGET_S2C = ProtoCode.New(12030, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitChaseTarget_S2C", ProtoCallBack_UnitChaseTarget_S2C);
    ---@type ProtoCode 战斗单位停止追逐目标广播
    UNIT_STOP_CHASE_TARGET_S2C = ProtoCode.New(12031, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitStopChaseTarget_S2C", ProtoCallBack_UnitStopChaseTarget_S2C);
    ---@type ProtoCode 战斗单位开始远离目标广播
    UNIT_ESCAPE_TARGET_S2C = ProtoCode.New(12032, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitEscapeTarget_S2C", ProtoCallBack_UnitEscapeTarget_S2C);
    ---@type ProtoCode 战斗单位停止远离目标广播
    UNIT_STOP_ESCAPE_TARGET_S2C = ProtoCode.New(12033, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitStopEscapeTarget_S2C", ProtoCallBack_UnitStopEscapeTarget_S2C);
    ---@type ProtoCode 战斗单位开始指定移动广播
    UNIT_MOVE_TOWARDS_TARGET_S2C = ProtoCode.New(12034, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitMoveTowards_S2C", ProtoCallBack_UnitMoveTowards_S2C);
    ---@type ProtoCode 战斗单位停止指定移动广播
    UNIT_STOP_MOVE_TOWARDS_TARGET_S2C = ProtoCode.New(12035, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitStopMoveTowards_S2C", ProtoCallBack_UnitStopMoveTowards_S2C);
    ---@type ProtoCode 战斗单位开始平移行为广播
    UNIT_MOVE_TOWARDS_2_S2C = ProtoCode.New(12075, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitMoveTowards_2_S2C", ProtoCallBack_UnitMoveTowards_2_S2C);
    ---@type ProtoCode 战斗单位停止平移行为广播
    UNIT_STOP_MOVE_TOWARDS_2_S2C = ProtoCode.New(12076, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitStopMoveTowards_2_S2C", ProtoCallBack_UnitStopMoveTowards_2_S2C);
    ---@type ProtoCode 怪物使用技能广播
    MONS_CAST_SKILL_S2C = ProtoCode.New(12036, PROTO_MESSAGE_TYPE.broadcast, "msg.MonsCastSkill_S2C", ProtoCallBack_MonsCastSkill_S2C);
    ---@type ProtoCode 子弹碰撞协议
    BATTLE_UNIT_COLLISION = ProtoCode.New(12037, PROTO_MESSAGE_TYPE.player, "msg.BattleUnitCollision", ProtoCallBack_OnBulletCollision);
    ---@type ProtoCode 拾取掉落物
    PICK_UP_DROP_FALL_OBJECT = ProtoCode.New(12039, PROTO_MESSAGE_TYPE.player, "msg.PickUpDropFallObject", ProtoCallBack_PickUpDropFallObject);
    ---@type ProtoCode 战斗单位开始转向目标广播
    UNIT_FACE_TARGET_S2C = ProtoCode.New(12040, PROTO_MESSAGE_TYPE.broadcast, "msg.UnitFaceTarget_S2C", ProtoCallBack_UnitFaceTarget_S2C);
    ---@type ProtoCode 战斗单位停止转向目标广播
    UNIT_STOP_FACE_TARGET_S2C = ProtoCode.New(12041, PROTO_MESSAGE_TYPE.broadcast, "msg.UnitStopFaceTarget_S2C", ProtoCallBack_UnitStopFaceTarget_S2C);
    ---@type ProtoCode 战斗单位移动数据
    BATTLE_UNIT_MOVE_DATA = ProtoCode.New(12042, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleUnitMoveDataList", ProtoCallBack_ClientReceiveMoveData);
    ---@type ProtoCode 战斗单位改变数据
    BATTLE_UNIT_CHANGE_DATA = ProtoCode.New(12043, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleUnitChangeDataList", ProtoCallBack_ClientReceiveChangeData);
    ---@type ProtoCode 战斗单位关键数据
    BATTLE_UNIT_KEY_DATA = ProtoCode.New(12044, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleUnitKeyDataList", ProtoCallBack_ClientReceiveKeyData);
    ---@type ProtoCode 战斗场景数据
    BATTLE_FIELD_DATA = ProtoCode.New(12045, PROTO_MESSAGE_TYPE.logicOutput, "msg.BattleFieldDataList", ProtoCallBack_ClientReceiveFieldData);
    ---@type ProtoCode 暂停怪物AI
    MONS_PAUSE_AI = ProtoCode.New(12046, PROTO_MESSAGE_TYPE.broadcast, "msg.MonsPauseAi_S2C", ProtoCallBack_PauseMonsAi);
    ---@type ProtoCode 恢复怪物AI
    MONS_RESUME_AI = ProtoCode.New(12047, PROTO_MESSAGE_TYPE.broadcast, "msg.MonsResumeAi_S2C", ProtoCallBack_ResumeMonsAi);
    ---@type ProtoCode 生成关卡触发器
    GENERATE_LEVEL_TRIGGER_S2C = ProtoCode.New(12049, PROTO_MESSAGE_TYPE.broadcast, "msg.GenerateLevelTrigger_S2C", ProtoCallBack_GenerateLevelTriggerS2C);
    ---@type ProtoCode 单位进入关卡触发器
    UNIT_ENTER_LEVEL_TRIGGER = ProtoCode.New(12050, PROTO_MESSAGE_TYPE.Room, "msg.UnitEnterLevelTrigger", ProtoCallBack_UnitEnterLevelTrigger);
    ---@type ProtoCode 单位进入关卡触发器
    UNIT_LEAVE_LEVEL_TRIGGER = ProtoCode.New(12051, PROTO_MESSAGE_TYPE.Room, "msg.UnitLeaveLevelTrigger", ProtoCallBack_UnitLeaveLevelTrigger);
    ---@type ProtoCode 服务端Logic -> 客户端Logic 服务端结束战斗表演(通用)
    SERVER_BATTLE_PLAY_ACT_END_S2C = ProtoCode.New(12052, PROTO_MESSAGE_TYPE.logicOutput, "msg.ServerBattlePlayActEnd_S2C", ProtoCallBack_ServerBattlePlayActEnd_S2C);
    ---@type ProtoCode 服务端Logic -> 客户端Logic 服务端结束战斗剧情(通用)
    SERVER_BATTLE_PLAY_PLOT_END_S2C = ProtoCode.New(12053, PROTO_MESSAGE_TYPE.logicOutput, "msg.ServerBattlePlayPlotEnd_S2C", ProtoCallBack_ServerBattlePlayPlotEnd_S2C);
    ---@type ProtoCode 显示层触发事件
    BATTLE_UNIT_TRIGGER_EVENT_V2S = ProtoCode.New(12054, PROTO_MESSAGE_TYPE.player, "msg.BattleUnitTriggerEvent_V2S", ProtoCallBack_BattleUnitTriggerEvent);
    ---@type ProtoCode 武装进入过载(SL->CL)
    WEAPON_ENTER_OVER_LOAD_S2C = ProtoCode.New(12056, PROTO_MESSAGE_TYPE.broadcast, "msg.WeaponEnterOverLoad_S2C", ProtoCallBack_WeaponEnterOverLoad);
    ---@type ProtoCode 武装退出过载(SL->CL)
    WEAPON_EXIT_OVER_LOAD_S2C = ProtoCode.New(12057, PROTO_MESSAGE_TYPE.broadcast, "msg.WeaponExitOverLoad_S2C", ProtoCallBack_WeaponExitOverLoad);
    ---@type ProtoCode 切换血量阶段(SL->CL)
    UNIT_CHANGE_STAGE_S2C = ProtoCode.New(12058, PROTO_MESSAGE_TYPE.broadcast, "msg.UnitChangeStage_S2C", ProtoCallBack_UnitChangeStageS2C);
    ---@type ProtoCode 极奏换人(Client->SL)
    JIZOU_CHANGE_LEADER_INPUT = ProtoCode.New(12059, PROTO_MESSAGE_TYPE.player, "msg.JizouChangeLeaderInput", ProtoCallBack_JizouChangeLeaderInput);
    ---@type ProtoCode 弹幕触发事件(Client->SL)
    BARRAGE_TRIG_EVENT_V2S = ProtoCode.New(12060, PROTO_MESSAGE_TYPE.player, "msg.BarrageTrigEvent_V2S", ProtoCallBack_BarrageTrigEvent_V2S);
    ---@type ProtoCode 实体进入区域(Client->SL)
    UNIT_ENTER_AREA_V2S = ProtoCode.New(12061, PROTO_MESSAGE_TYPE.player, "msg.UnitEnterArea_V2S", ProtoCallBack_UnitEnterArea_V2S);
    ---@type ProtoCode 实体离开区域(Client->SL)
    UNIT_LEAVE_AREA_V2S = ProtoCode.New(12062, PROTO_MESSAGE_TYPE.player, "msg.UnitLeaveArea_V2S", ProtoCallBack_UnitLeaveArea_V2S);
    ---@type ProtoCode 通知object死亡(SL->CL)
    --UNIT_OBJECT_DEAD_S2C = ProtoCode.New(12063, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitObjectDead_S2C", ProtoCallBack_UnitObjectDead_S2C);
    ---@type ProtoCode 武装进入能量恢复状态(SL->CL)
    WEAPON_ENTER_RECOVER_ENERGY_STATE_S2C = ProtoCode.New(12064, PROTO_MESSAGE_TYPE.logicOutput, "msg.WeaponEnterRecoverEnergyState_S2C", ProtoCallBack_WeaponEnterRecoverEnergyState_S2C);
    ---@type ProtoCode 武装退出能量恢复状态(SL->CL)
    WEAPON_EXIT_RECOVER_ENERGY_STATE_S2C = ProtoCode.New(12065, PROTO_MESSAGE_TYPE.logicOutput, "msg.WeaponExitRecoverEnergyState_S2C", ProtoCallBack_WeaponExitRecoverEnergyState_S2C);
    ---@type ProtoCode 完成战斗引导(CL->SL)
    COMPLETE_BATTLE_GUIDE = ProtoCode.New(12066, PROTO_MESSAGE_TYPE.player, "msg.CompleteBattleGuide", ProtoCallBack_CompleteBattleGuide);
    ---@type ProtoCode 触发新手引导(SL->CL)
    TRIG_BATTLE_GUIDE_S2C = ProtoCode.New(12067, PROTO_MESSAGE_TYPE.broadcast, "msg.TrigBattleGuide_S2C", ProtoCallBack_TrigBattleGuide_S2C);
    ---@type ProtoCode 关卡触发新手引导UI操作(SL->CL)
    LEVEL_TRIG_UI_OPERATE_S2C = ProtoCode.New(12068, PROTO_MESSAGE_TYPE.broadcast, "msg.LevelTrigUIOperate_S2C", ProtoCallBack_LevelTrigGuideUIOperate_S2C);
    ---@type ProtoCode 关卡触发玩家控制器操作(SL->CL)
    LEVEL_TRIG_CONTROLLER_OPERATE_S2C = ProtoCode.New(12069, PROTO_MESSAGE_TYPE.broadcast, "msg.LevelTrigControllerOperate_S2C", ProtoCallBack_LevelTrigControllerOperate_S2C);
    ---@type ProtoCode 玩家撞墙
    PLAYER_HIT_WALL = ProtoCode.New(12070, PROTO_MESSAGE_TYPE.player, "msg.PlayerHitWall", ProtoCallBack_PlayerHitWall);
	---@type ProtoCode 开始跟随召唤者
    UNIT_CHASE_SUBORDINATE = ProtoCode.New(12071, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitChaseSubordinate_S2C", ProtoCallBack_UnitChaseSubordinate_S2C);
	---@type ProtoCode 结束跟随召唤者
    UNIT_STOP_CHASE_SUBORDINATE = ProtoCode.New(12072, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitStopChaseSubordinate_S2C", ProtoCallBack_UnitStopChaseSubordinate_S2C);
    ---@type ProtoCode 双端对时协议
    CLIENT_TIME_SYNC = ProtoCode.New(12073, PROTO_MESSAGE_TYPE.tick, "msg.ClientTimeSync");
    ---@type ProtoCode 推送获取的三星
    GET_MAIN_LEVEL_STAR_LIST_S2C = ProtoCode.New(12074, PROTO_MESSAGE_TYPE.logicOutput, "msg.GetMainLevelStarList_S2C", ProtoCallBack_GetMainLevelStarList_S2C);
    ---@type ProtoCode 开始导航点移动
    UNIT_MOVE_NAV_POINTS_S2C = ProtoCode.New(12077, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitMoveNavPoints_S2C", ProtoCallBack_UnitMoveNavPoints_S2C);
    ---@type ProtoCode 停止导航点移动
    UNIT_STOP_MOVE_NAV_POINTS_S2C = ProtoCode.New(12078, PROTO_MESSAGE_TYPE.logicOutput, "msg.UnitStopMoveNavPoints_S2C", ProtoCallBack_UnitStopMoveNavPoints_S2C);
    ---@type ProtoCode 停止导航点移动
    SYNC_LEVEL_PAUSE_TIME_S2C = ProtoCode.New(12079, PROTO_MESSAGE_TYPE.logicOutput, "msg.SyncLevelPauseTime_S2C", ProtoCallBack_SyncLevelPauseTime_S2C);
    ---@type ProtoCode 停止导航点移动
    DESTROY_BULLET = ProtoCode.New(12080, PROTO_MESSAGE_TYPE.player, "msg.DestroyBullet", ProtoCallBack_DestroyBullet);
    ---@type ProtoCode 可受击子弹死亡
    BARRAGE_BULLET_DEAD = ProtoCode.New(12081, PROTO_MESSAGE_TYPE.player, "msg.BarrageBulletDead_V2S", ProtoCallBack_BarrageBulletDead);
    ---@type ProtoCode 单位修改分块状态
    UNIT_CHANGE_BLOCK_STATE = ProtoCode.New(12082, PROTO_MESSAGE_TYPE.broadcast, "msg.UnitChangeBlockState_S2C", ProtoCallBack_UnitChangeBlockState);
    ---@type ProtoCode 单位交互结果
    UNIT_HANDLE_RESULT_S2C = ProtoCode.New(12083, PROTO_MESSAGE_TYPE.broadcast, "msg.BattleUnitHandleResult_S2C", ProtoCallBack_UnitHandleResult_S2C);
    ---@type ProtoCode 单位交互输入
    UNIT_HANDLE_INPUT_V2S = ProtoCode.New(12084, PROTO_MESSAGE_TYPE.player, "msg.BattleUnitHandleInput_V2S", ProtoCallBack_BattleUnitHandleInput_V2S);
    ---@type ProtoCode 关卡触发一般UI操作
    LEVEL_TRIG_NORMAL_UI_OPERATE_S2C = ProtoCode.New(12085, PROTO_MESSAGE_TYPE.broadcast, "msg.LevelTrigNormalUIOperate_S2C", ProtoCallBack_LevelTrigNormalUIOperate_S2C);
    ---@type ProtoCode 点击朝向目标
    AUTO_FACE_ENEMY_V2S = ProtoCode.New(12086, PROTO_MESSAGE_TYPE.player, "msg.AutoFaceEnemy_V2S", ProtoCallBack_AutoFaceEnemy_V2S);
    ---@type ProtoCode 改变tag
    CHANGE_TAG_S2C = ProtoCode.New(12086, PROTO_MESSAGE_TYPE.logicOutput, "msg.ChangeTag_S2C", ProtoCallBack_ChangeTag_S2C);
    ---@type ProtoCode 改变tag
    PlayerReconnectBattleRoomInfo_S2C = ProtoCode.New(12088, PROTO_MESSAGE_TYPE.logicOutput, "msg.PlayerReconnectBattleRoomInfo_S2C", ProtoCallBack_PlayerReconnectBattleRoomInfo_S2C);
    ---@type ProtoCode 改变tag
    RELOAD_BULLET_START_S2C = ProtoCode.New(12089, PROTO_MESSAGE_TYPE.logicOutput, "msg.ReloadBulletStart_S2C", ProtoCallBack_ReloadBulletStart_S2C);
    ---@type ProtoCode 改变tag
    RELOAD_BULLET_END_S2C = ProtoCode.New(12090, PROTO_MESSAGE_TYPE.logicOutput, "msg.ReloadBulletEnd_S2C", ProtoCallBack_ReloadBulletEnd_S2C);
	---@type ProtoCode 服务端发起寻路请求
    UNIT_PATH_FIND_REQUEST_S2C = ProtoCode.New(12091, PROTO_MESSAGE_TYPE.broadcast, "msg.CallPathFind_S2C", ProtoCallBack_CallPathFind_S2C);
    ---@type ProtoCode 服务端停止寻路请求
    UNIT_PATH_FIND_CANCEL_S2C = ProtoCode.New(12092, PROTO_MESSAGE_TYPE.broadcast, "msg.CancelPathFind_S2C", ProtoCallBack_CancelPathFind_S2C);
    ---@type ProtoCode 服务端停止寻路请求
    LEVEL_CHANGE_TIME_LIMIT_S2C = ProtoCode.New(12093, PROTO_MESSAGE_TYPE.broadcast, "msg.LevelChangeTimeLimit_S2C", ProtoCallBack_LevelChangeTimeLimit);
    ---@type ProtoCode 战斗单位碰撞
    BATTLE_UNIT_HIT_WALL = ProtoCode.New(12094, PROTO_MESSAGE_TYPE.player, "msg.BattleObjectHitWall", ProtoCallBack_BattleObjectHitWall);
    ---@type ProtoCode 战斗单位位置非法
    UNIT_POS_ILLEGAL = ProtoCode.New(12095, PROTO_MESSAGE_TYPE.player, "msg.UnitPositionIllegal", ProtoCallBack_UnitPosIllegal);
    ---@type ProtoCode 获取行为树信息
    ASK_BEHAV_INFO = ProtoCode.New(12096, PROTO_MESSAGE_TYPE.player, "msg.AskBehaviorInfo", ProtoCallBack_AskBehaviorInfo);
    ---@type ProtoCode 行为树状态
    PUSH_BEHAV_INFO_S2C = ProtoCode.New(12097, PROTO_MESSAGE_TYPE.player, "msg.PushBehaviorInfo_S2C", ProtoCallBack_PushBehaviorInfo_S2C);
    ---@type ProtoCode 弱点击破
    WEAKNESS_BROKEN_S2C = ProtoCode.New(12098, PROTO_MESSAGE_TYPE.broadcast, "msg.WeaknessBroken_S2C", ProtoCallBack_WeaknessBroken_S2C);
	---@type ProtoCode 表现层创建Unit完成回调
    CLIENT_CREATE_UNIT_END_V2L = ProtoCode.New(12099, PROTO_MESSAGE_TYPE.player, "msg.UnitBornFinish_V2L", ProtoCallBack_ClientCreateUnitEnd_V2L);
    ---@type ProtoCode 开始切换血量阶段
    UNIT_START_CHANGE_STAGE_S2C = ProtoCode.New(12101, PROTO_MESSAGE_TYPE.player, "msg.UnitStartChangeStage_S2C", ProtoCallBack_UnitStartChangeStage_S2C);
}

-- 消息映射
---@type ProtoCode[] 协议映射
PROTO_CODE_MAP = {};

for _, value in pairs(PROTO_CODE_ENUM) do
    PROTO_CODE_MAP[tostring(value:GetId())] = value;
end