---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/07/20 14:39
--- Describe: 强制设置位置（没想好怎么规划, 暂时先用着）
---

---@class BattleUnitCom_PositionSet : BattleUnitComponentBase
BattleUnitCom_PositionSet = class(BattleUnitComponentBase, "BattleUnitCom_PositionSet")
function BattleUnitCom_PositionSet:ctor(_data)
	self:__ctor(BattleUnitComponentType.PosSet)
end

---@public
---@param _battleUnit BattleUnitBase
function BattleUnitCom_PositionSet:Init(_battleUnit)
	self:__Init(_battleUnit)
	self.__open = false
	self.__pathFindHost = self:GetBattleRoom().behaviorProcessor:CheckMonsAIHost()
	self.__targetPosCache = _battleUnit:GetBattleRoom().vector3Pool:Pop()
end

function BattleUnitCom_PositionSet:Open(_bool)
	--LogTools.LogByLevel(LogLevel.log, "CheckSummonedMons", "BattleUnitCom_PositionSet", "Open", "_bool", _bool)
	self.__open = _bool
end

---@public
---@param _caller BattleUnit_PathFindCaller
function BattleUnitCom_PositionSet:StartPosSet(_caller)
	--LogTools.LogByLevel(LogLevel.log, "CheckSummonedMons", "BattleUnitCom_PositionSet", "StartPosSet")
	self.__caller = _caller
end

---@public
function BattleUnitCom_PositionSet:StopPosSet()
	--LogTools.LogByLevel(LogLevel.log, "CheckSummonedMons", "BattleUnitCom_PositionSet", "StopPosSet")
	self.__caller = nil
end

---碰到障碍物
---@public
---@param _hitPos Vector3 撞墙修正位置
---@param _hitDir Vector3 撞墙修正移动方向
---@param _isEdge boolean 是否是撞到边界
function BattleUnitCom_PositionSet:OnHitBlock(_hitPos, _hitDir, _isEdge)
	if self.__caller then
		self.__caller:OnHitBlock(_hitPos, _hitDir, _isEdge)
	end
end

---@public
function BattleUnitCom_PositionSet:Update(_deltaTime)
	----LogTools.LogByLevel(LogLevel.log, "BattleUnitCom_PositionSet", "Update", "_deltaTime", _deltaTime)

	if not self:__CheckUpdate(_deltaTime) then return end
	local _actionManager = self.__actionManager
	if not _actionManager then return end

	--LuaProfiler.BeginSample("BattleUnitCom_PositionSet")
	if _actionManager:CheckHasForceAcc() then
		--LuaProfiler.EndSample("BattleUnitCom_PositionSet")
		return
	end

	self.__caller:DirectMove(_deltaTime)
end

---@private
function BattleUnitCom_PositionSet:__CheckUpdate(_deltaTime)
	if not self.__open then return false end
	if not self.__caller then return false end
	if not self.__pathFindHost then return false end
	if self:GetBattleRoom():CheckPauseLevelNormalLogic() then return false end
	if not self.__behavCom then
		---@type BattleUnitCom_Behav
		self.__behavCom = self.__unit:GetComponent(BattleUnitComponentType.Behav)
		if not self.__behavCom then return false end
	end
	if self.__behavCom:CheckAIPaused() then return false end
	return true
end

---@public
function BattleUnitCom_PositionSet:Clear()
	self.__unit:GetBattleRoom().vector3Pool:Push(self.__targetPosCache)
	self.__open = nil
	self:__Clear()
end
return BattleUnitCom_PositionSet