---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/02/19 10:38
--- Describe:
---

---@class BattleUnitComponentBase : table
BattleUnitComponentBase = class(nil, "BattleUnitComponentBase")

---@protected
---@param _componentType BattleUnitComponentType
function BattleUnitComponentBase:__ctor(_componentType) 
	self.__type = _componentType
end

---@protected
---@param _battleUnit BattleUnitBase
function BattleUnitComponentBase:__Init(_battleUnit)
	self.__unit = _battleUnit
	self.__netId = _battleUnit:GetNetId()
	self.__actionManager = _battleUnit:GetActionManager()
	self.battleRoom = _battleUnit:GetBattleRoom()
end

---@protected
function BattleUnitComponentBase:__GetComponentType()
	return self.__type
end

---@protected
---@return BattleUnitBase
function BattleUnitComponentBase:__GetUnit()
	return self.__unit
end

---@protected
function BattleUnitComponentBase:__Clear()
	self.__type = nil
	self.__unit = nil
	self.__actionManager = nil
end
------------------------------------------------------------------------------------------------------------------------
---@public
---@param _componentType BattleUnitComponentType
function BattleUnitComponentBase:ctor(_componentType)
	self:__ctor(_componentType)
end

---@public
---@param _battleUnit BattleUnitBase
function BattleUnitComponentBase:Init(_battleUnit)
	self:__Init(_battleUnit)
end

---@public
---@return BattleUnitComponentType
function BattleUnitComponentBase:GetComponentType()
	return self:__GetComponentType()
end

---@public
---@return BattleUnitBase
function BattleUnitComponentBase:GetUnit()
	return self:__GetUnit()
end

---@public
function BattleUnitComponentBase:GetBattleId()
	return self.__unit:GetBattleId()
end

---@public
---@return BattleRoom
function BattleUnitComponentBase:GetBattleRoom()
	return self.__unit:GetBattleRoom()
end

---@public
function BattleUnitComponentBase:OnDead(_deadType)
	
end

---@public
function BattleUnitComponentBase:Update(_dt)
	
end

---@public
function BattleUnitComponentBase:Clear()
	self:__Clear()
end

------------------------------------------------------------------------------------------------------------------------
---服务器逻辑核生成用于发送给前端逻辑核的全量信息
---@public
function BattleUnitComponentBase:GetCreateSyncMessage_S2C()
    return nil
end

---前端逻辑核用服务器发来的全量信息刷新自身数据
---@public
function BattleUnitComponentBase:OnReceiveCreateSyncMessage_S2C(_message)
    
end

---前端逻辑核生成用于发送给表现的层全量信息
---@public
function BattleUnitComponentBase:GetCreateSyncMessage_L2V(_message)
    return nil
end
return BattleUnitComponentBase