---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2022/1/6 18:58
--- 战斗单元管理器

require "Lib/class"

---@class BattleRoomObjectManager : table 战斗单元管理器
---@field allTable table[] 所有战斗单元
---@field playerTable BattlePlayer[] 玩家单位
---@field monsterTable BattleMonsterUnit[] 怪物单位
---@field bulletTable table[] 弹幕单位
BattleRoomObjectManager = class(nil,'BattleRoomObjectManager');

function BattleRoomObjectManager:ctor()

    self.allTable = {};
    self.playerTable = {};
    self.monsterTable = {};
    self.bulletTable = {};

end

-- 添加玩家
---@public
---@param _player BattlePlayer 战斗玩家
function BattleRoomObjectManager:AddPlayer(_player)
    self.playerTable[_player:GetPlayerId()] = _player;
    for i, v in pairs(_player:GetAllLeader()) do
        self.allTable[v:GetNetId()] = v;
    end
end

-- 获得玩家
---@public
---@param _playerId number 玩家id
---@return BattlePlayer 需要获得的玩家
function BattleRoomObjectManager:GetPlayer(_playerId)
    return self.playerTable[_playerId];
end

-- 获得全部玩家
---@public
---@return BattlePlayer[] 战斗中所有玩家
function BattleRoomObjectManager:GetAllPlayer()
    return self.playerTable;
end

-- 添加怪物
---@public
---@param _monster BattleMonsterUnit 怪物
function BattleRoomObjectManager:AddMonster(_monster)
    local _netId = _monster:GetNetId()
    self.monsterTable[_netId] = _monster
    self.allTable[_netId] = _monster
end

-- 添加弹幕
function BattleRoomObjectManager:AddBullet(_bullet)

end

-- 获得怪物
---@public
---@return BattleMonsterUnit 获得怪物
function BattleRoomObjectManager:GetMonster(_netId)
    return self.monsterTable[_netId]
end

-- 获取所有怪物
---@public
---@return BattleMonsterUnit[] 战场内所有怪物
function BattleRoomObjectManager:GetAllMonster()
    return self.monsterTable
end

-- 获得弹幕
function BattleRoomObjectManager:GetBullet(_id)
    
end

-- 移除玩家
---@public
---@param _playerId number 玩家id
function BattleRoomObjectManager:RemovePlayer(_playerId)
    local player = self.playerTable[_playerId];
    self.playerTable[player:GetPlayerId()] = nil;
    for i, v in pairs(player:GetAllLeader()) do
        self.allTable[v:GetNetId()] = nil;
    end
end

-- 移除怪物
function BattleRoomObjectManager:RemoveMonster(_netId)
    self.monsterTable[_netId] = nil
    self.allTable[_netId] = nil
end

-- 移除弹幕
function BattleRoomObjectManager:RemoveBullet(_id)

end

return BattleRoomObjectManager;

