---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2022/1/10 18:58
--- 战斗核心消息包装

require "Lib/class"

---@class BattleRoomMessage:table 战斗核心消息包装
---@field id number 协议id
---@field uid number 发送协议玩家id
---@field message table 协议体
BattleRoomMessage = class(nil,'BattleRoomMessage');

function BattleRoomMessage:ctor()
    self.id = nil;
    self.uid = nil;
    self.message = nil;
end

-- 初始化
---@public
---@field _uid number 发送协议玩家id
---@field _id number 协议id
---@field _message table 协议体
function BattleRoomMessage:Init(_uid,_id,_message)
    self.id = _id;
    self.uid = _uid;
    self.message = _message;
end

-- 消息playerId
---@public
---@return number 消息playerId
function BattleRoomMessage:GetUid()
    return self.uid;
end

-- 协议id
---@public
---@return number 协议id
function BattleRoomMessage:GetId()
    return self.id;
end

-- 消息体
---@public
---@return table 协议
function BattleRoomMessage:GetMessage()
    return self.message;
end