---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2023/03/10 11:26
--- Describe:
---

---@class PlayerGMInterface : table
PlayerGMInterface = class(nil, "PlayerGMInterface")
function PlayerGMInterface:ctor(_data) end

---@public
---@param _battleRoom BattleRoom
function PlayerGMInterface:Init(_battleRoom)
	self.__battleRoom = _battleRoom
	self.__battleId = _battleRoom:GetBattleId()
end

---@public
---@return BattleRoom
function PlayerGMInterface:GetBattleRoom()
	return self.__battleRoom
end

---@public
---@return number
function PlayerGMInterface:GetBattleId()
	return self.__battleId
end

---@public
---@param _unit BattleUnitBase
function PlayerGMInterface:OnPlayerGM(_unit, _module, _command, _target, _paramStr)
	--LogTools.LogByLevel(LogLevel.log, "BattleUnitManager:OnPlayerGM", "_unit", _unit, "_module", _module, "_command", _command)
	if not _module or not _command then return end

	local _params = LuaTool:Split(_paramStr,"_")

	if "BUFF" == _module then
		self:__buffGM(_unit, _command, _target, _params)
	elseif "SKILL" == _module then
		self:__skillGM(_unit, _command, _target, _params)
	elseif "PROP" == _module then
		self:__propGM(_unit, _command, _target, _params)
	elseif "LEVEL" == _module then
		self:__levelGM(_unit, _command, _target, _params)
	end

end

---@private
---@param _params string[]
---@param _unit BattleUnitBase
function PlayerGMInterface:__buffGM(_unit, _command, _target, _params)
	
	if _target == 1 then --全体英雄（不包括召唤物）
		if not _unit then return end
		
		for _, v in pairs(_unit:GetTypeObjectList(BattleObjectType.LeaderHero)) do
			---@type BattleObjCom_Buff
			local buffCom = v:GetComponent(BattleObjectComponentType.Buff)
			buffCom:OnPlayerGm(_command, _params)
		end
	elseif _target == 2 then --全体英雄(包括召唤物)
		if not _unit then return end
		
		local buffCom
		for _, v in pairs(_unit:GetTypeObjectList(BattleObjectType.LeaderHero)) do
			---@type BattleObjCom_Buff
			buffCom = v:GetComponent(BattleObjectComponentType.Buff)
			buffCom:OnPlayerGm(_command, _params)
		end
		
		---@type BattleUnitCom_Subordination
		local _subordinationCom = _unit:GetComponent(BattleUnitComponentType.Subordination)
		local _summonedList = _subordinationCom:GetManagedObjListByObjType(BattleObjectType.SummonedMons)
		for _, v in pairs(_summonedList) do
			---@type BattleObjCom_Buff
			buffCom = v:GetComponent(BattleObjectComponentType.Buff)
			if buffCom then
				buffCom:OnPlayerGm(_command, _params)
			end
		end
	elseif _target == 3 then --当前英雄（不包括召唤物）
		if not _unit then return end
		
		---@type BattleObjCom_Buff
		local buffCom = _unit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Buff)
		buffCom:OnPlayerGm(_command, _params)
	elseif _target == 4 then --当前英雄（包括召唤物）
		if not _unit then return end
		
		---@type BattleObjCom_Buff
		local buffCom = _unit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Buff)
		buffCom:OnPlayerGm(_command, _params)

		---@type BattleUnitCom_Subordination
		local _subordinationCom = _unit:GetComponent(BattleUnitComponentType.Subordination)
		local _summonedList = _subordinationCom:GetManagedObjListByObjType(BattleObjectType.SummonedMons)
		for _, v in pairs(_summonedList) do
			---@type BattleObjCom_Buff
			buffCom = v:GetComponent(BattleObjectComponentType.Buff)
			if buffCom then
				buffCom:OnPlayerGm(_command, _params)
			end
		end
	elseif _target == 5 then --当前所有怪物阵营
		local _monsUnitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Monster)
		for _, _monsUnit in pairs(_monsUnitList) do
			---@type BattleObjCom_Buff
			local _buffCom = _monsUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Buff)
			if _buffCom then
				_buffCom:OnPlayerGm(_command, _params)
			end
		end
	elseif _target == 6 then --当前所有玩家阵营和怪物阵营
		local _monsUnitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Monster)
		for _, _monsUnit in pairs(_monsUnitList) do
			---@type BattleObjCom_Buff
			local _buffCom = _monsUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Buff)
			if _buffCom then
				_buffCom:OnPlayerGm(_command, _params)
			end
		end
		local _playerUnitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Player)
		for _, _playerUnit in pairs(_playerUnitList) do
			---@type BattleObjCom_Buff
			local _buffCom = _playerUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Buff)
			if _buffCom then
				_buffCom:OnPlayerGm(_command, _params)
			end
		end
	end
end

---@private
---@param _params string[]
---@param _unit BattleUnitBase
function PlayerGMInterface:__skillGM(_unit, _command, _target, _params)
	if not _unit then return end
	
	if _target == 1 then --全体英雄（不包括召唤物）
		if not _unit then return end
		
		for _, _object in pairs(_unit:GetTypeObjectList(BattleObjectType.LeaderHero)) do
			---@type BattleObjCom_Skill
			local _skillCom = _object:GetComponent(BattleObjectComponentType.Skill)
			_skillCom:OnPlayerGm(_command, _params)
		end
	elseif _target == 2 then --全体英雄(包括召唤物)
		if not _unit then return end
		
		---@type BattleObjCom_Skill
		local _skillCom
		for _, _object in pairs(_unit:GetTypeObjectList(BattleObjectType.LeaderHero)) do
			_skillCom = _object:GetComponent(BattleObjectComponentType.Skill)
			_skillCom:OnPlayerGm(_command, _params)
		end
		
		---@type BattleUnitCom_Subordination
		local _subordinationCom = _unit:GetComponent(BattleUnitComponentType.Subordination)
		local _summonedList = _subordinationCom:GetManagedObjListByObjType(BattleObjectType.SummonedMons)
		for _, _object in pairs(_summonedList) do
			_skillCom = _object:GetComponent(BattleObjectComponentType.Skill)
			if _skillCom then
				_skillCom:OnPlayerGm(_command, _params)
			end
		end
	elseif _target == 3 then --当前英雄（不包括召唤物）
		if not _unit then return end
		
		---@type BattleObjCom_Skill
		local _skillCom = _unit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Skill)
		_skillCom:OnPlayerGm(_command, _params)
	elseif _target == 4 then --当前英雄（包括召唤物）
		if not _unit then return end
		
		---@type BattleObjCom_Skill
		local _skillCom = _unit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Skill)
		_skillCom:OnPlayerGm(_command, _params)

		---@type BattleUnitCom_Subordination
		local _subordinationCom = _unit:GetComponent(BattleUnitComponentType.Subordination)
		local _summonedList = _subordinationCom:GetManagedObjListByObjType(BattleObjectType.SummonedMons)
		for _, _object in pairs(_summonedList) do
			_skillCom = _object:GetComponent(BattleObjectComponentType.Skill)
			if _skillCom then
				_skillCom:OnPlayerGm(_command, _params)
			end
		end
	elseif _target == 5 then --当前所有怪物阵营
		local _monsUnitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Monster)
		for _, _monsUnit in pairs(_monsUnitList) do
			---@type BattleObjCom_Skill
			local _skillCom = _monsUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Skill)
			if _skillCom then
				_skillCom:OnPlayerGm(_command, _params)
			end
		end
	elseif _target == 6 then --当前所有玩家阵营和怪物阵营
		local _monsUnitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Monster)
		for _, _monsUnit in pairs(_monsUnitList) do
			---@type BattleObjCom_Skill
			local _skillCom = _monsUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Skill)
			if _skillCom then
				_skillCom:OnPlayerGm(_command, _params)
			end
		end
		local _playerUnitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Player)
		for _, _playerUnit in pairs(_playerUnitList) do
			---@type BattleObjCom_Skill
			local _skillCom = _playerUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Skill)
			if _skillCom then
				_skillCom:OnPlayerGm(_command, _params)
			end
		end
	end
end

---@private
---@param _params string[]
---@param _unit BattleUnitBase
function PlayerGMInterface:__propGM(_unit, _command, _target, _params)
	
	if _target == 1 then --当前英雄
		if not _unit then return end

		---@type BattleObjCom_Property
		local _propCom = _unit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Property)
		_propCom:OnPlayerGm(_command, _params)
	elseif _target == 2 then --所有英雄
		if not _unit then return end

		for _, _hero in pairs(_unit:GetTypeObjectList(BattleObjectType.LeaderHero)) do
			---@type BattleObjCom_Property
			local _propCom = _hero:GetComponent(BattleObjectComponentType.Property)
			_propCom:OnPlayerGm(_command, _params)	
		end
	elseif _target == 3 then --所有在场怪物
		local _monsList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Monster)
		for _, _monsUnit in pairs(_monsList) do
			---@type BattleObjCom_Property
			local _propCom = _monsUnit:GetCurrentHeroObject():GetComponent(BattleObjectComponentType.Property)
			if _propCom then
				_propCom:OnPlayerGm(_command, _params)
			end
		end
	end
	
end

---@private
---@param _params string[]
---@param _unit BattleUnitBase
function PlayerGMInterface:__levelGM(_unit, _command, _target, _params)
	
	if "LEVELTIME" == _command then --关卡时间
		self:GetBattleRoom().battleLevelManager:ChangeRunBattleLimitTime(tonumber(_params[1]))
	elseif "PAUSELLAI" == _command then --停止所有单位AI
		self:GetBattleRoom().behaviorManager:PauseUnitBehav()
	elseif "RESUMEALLAI" == _command then --恢复所有单位AI
		self:GetBattleRoom().behaviorManager:ResumeUnitBehav()
	elseif "KILLALLMONS" == _command then --杀死所有在场怪物
		local _unitList = self:GetBattleRoom().battleUnitManager:GetUnitListByCampType(BattleUnitCampType.Monster)
		for _, _monsUnit in pairs(_unitList) do
			self:GetBattleRoom().battleUnitManager:OnBattleObjectDead(_monsUnit:GetNetId(), _monsUnit:GetCurrentHeroObjectId(), LuaBehav_Define_DeadType.DeadNormal)
		end
	elseif "DROPMONS" == _command then --投怪
		local _instanceId = tonumber(_params[1])
		local _levelUnit = self:GetBattleRoom().battleLevelManager.levelUnitManager:CreateLevelUnitByInstanceId(_instanceId, LevelUnitTypeEnum.MONSTER)
		
		local _BattleUnitGenerateInfo = {}
		_BattleUnitGenerateInfo.unitType = BattleUnitType.Monster
		_BattleUnitGenerateInfo.netId = self:GetBattleRoom().idCreator:GetAndIncreaseNetId()
		_BattleUnitGenerateInfo.dicId = _instanceId
		_BattleUnitGenerateInfo.firstCamp = BattleUnitCampType.Monster
		_BattleUnitGenerateInfo.secCamp = 1
		
		_BattleUnitGenerateInfo.rotation = Vector3.zero_global()
		_BattleUnitGenerateInfo.scale = Vector3.one_global()
		_BattleUnitGenerateInfo.velocity = Vector3.zero_global()
		
		_BattleUnitGenerateInfo.levelUnitId = _levelUnit.id
		_BattleUnitGenerateInfo.timeStamp = TimeUtils.battleNow(self.battleId)
		_BattleUnitGenerateInfo.delayTime = 0
		_BattleUnitGenerateInfo.objIdList = {self:GetBattleRoom().idCreator:GetAndIncreaseObjId()}
		
		local _type = tonumber(_params[2])
		if _type == 1 then --在指定世界坐标投放
			_BattleUnitGenerateInfo.position = Vector3.New(tonumber(_params[3]), tonumber(_params[4]), tonumber(_params[5]))	
		elseif _type == 2 then --在玩家当前位置投放
			_BattleUnitGenerateInfo.position = Vector3.New(tonumber(_params[3]), tonumber(_params[4]), tonumber(_params[5])) + _unit:GetActionManager():GetPosition()
		end
		
		---@type BattleUnitDelayCreateData
		local _battleUnitDelayCreateData = BattleUnitDelayCreateData.New(_BattleUnitGenerateInfo)
		self:GetBattleRoom().battleUnitManager:AddDelayUnitCreateData(_battleUnitDelayCreateData)
	end
end

return PlayerGMInterface