---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaopuyang.
--- DateTime: 2021/12/20 18:09
--- 战斗玩家

require "Lib/class"
require "Battle/Logic/Room/BattleObject/ActionStateManage"
require "Battle/Logic/Room/BattleObject/Player/BattlePlayerLeader"
require "Battle/Logic/Room/BattleObject/Player/BattlePlayerLeaderManager"

---@class BattlePlayer : BattleObject
---@field playerId number
---@field name string
---@field level number
---@field curLeaderId number
---@field playerBattleRunTime number
---@field actionManager ActionStateManage
---@field leaderManager BattlePlayerLeaderManager
BattlePlayer = class(BattleObject,'BattlePlayer');

function BattlePlayer:ctor()

end

-- 初始化玩家
function BattlePlayer:Init(_playerId, _name, _level, _curLeaderId, _leaders)
    self.playerId = _playerId;
    self.name = _name;
    self.level = _level;
    self.curLeaderId = _curLeaderId;
    self.playerBattleRunTime = 0;

    self.actionManager = ActionStateManage:New();
    self.actionManager:Init(self, Vector3.New(620, 0, 20), Quaternion.New(0, 0, 0, 1), Vector3.New(0, 0, 0));

    self.leaderManager = BattlePlayerLeaderManager:New();
    self.leaderManager:Init(_curLeaderId, _leaders);
end

---@return number
function BattlePlayer:GetPlayerId()
    return self.playerId;
end

---@return number
function BattlePlayer:GetNetId()
    return self.leaderManager:GetCurrentLeaderNetId();
end

-- 获取当前武将
---@return BattlePlayerLeader
function BattlePlayer:GetCurrentLeader()
    return self.leaderManager:GetCurrentLeader()
end

-- 获取所有武将
function BattlePlayer:GetAllLeader()
    return self.leaderManager:GetAllLeader();
end

-- 切换行为
---@param _actionState ActionState
function BattlePlayer:EnterAction(_actionState)
    return self.actionManager:Enter(_actionState);
end

-- 执行行为
---@param _dt number
function BattlePlayer:DoAction(_dt)
    return self.actionManager:DoAction(_dt);
end

---@return ActionStateManage
function BattlePlayer:GetActionManager()
    return self.actionManager;
end

---@return BattlePlayerLeaderManager
function BattlePlayer:GetLeaderManager()
    return self.leaderManager;
end

return BattlePlayer;