---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/11/01 18:30
--- Describe:
---

---@class SceneObjTriggerLeaveActionData : table
SceneObjTriggerLeaveActionData = class(nil, "SceneObjTriggerLeaveActionData")
---@public
---@param _actrionCtrl BoundaryTriggerActionCtrlBase
function SceneObjTriggerLeaveActionData:Init(_actrionCtrl)
	self.__ctrl = _actrionCtrl
end

---出范围就发送给目标，是否真的移除，在目标的Collector组件中自己判断
---@public
function SceneObjTriggerLeaveActionData:Trig(_netIdList, _deltaTime)
	--if LogTools.AreaLog and CheckLogLevel(LogLevel.log) then
	--	LogTools.LogByLevel(LogLevel.log, "CheckArea", "AreaTriggerActionData Trig start", "_netIdList", dumpTableEx(_netIdList))
	--end
	
	local _unitManager = self.__ctrl:GetBattleRoom().battleUnitManager
	---@type BattleUnitBase
	local _unit
	---@type BattleUnitCom_Collector
	local _collector
	for _, _netId in pairs(_netIdList) do
		_unit = _unitManager:GetUnit(_netId)
		if _unit then
			_collector = _unit:GetComponent(BattleUnitComponentType.Collector)
			if _collector then
				_collector:Remove(self.__ctrl:GetTriggerCom():GetObject())
			end
		end
	end
	
end
return SceneObjTriggerLeaveActionData