---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/01/13 11:02
--- Describe: 战斗结束阶段
---

---@class BattleLevelStage_ShowBattleEnd : table
BattleLevelStage_ShowBattleEnd = class(BattleLevelStageBase, "BattleLevelStage_ShowBattleEnd")

function BattleLevelStage_ShowBattleEnd:OnEnter()
	LogTools.LogByLevel(BattleLevel_Define.LogLevel, "BattleLevel", "BattleLevelStage_ShowBattleEnd", "OnEnter")
	self:__OnEnter()
	if self:__InitConfig() then
		--通知表现层
				
	else
		self:OnStageEnd()
	end
end

function BattleLevelStage_ShowBattleEnd:__InitConfig()
	self.timeTotal = 3
	self.timeAcc = 0
	return true
end

function BattleLevelStage_ShowBattleEnd:OnUpdate(_deltaTime)
	local _timeAcc = self.timeAcc
	_timeAcc = _timeAcc + _deltaTime
	self.timeAcc = _timeAcc
	if _timeAcc > self.timeTotal then
		self:OnStageEnd()
	end
end

function BattleLevelStage_ShowBattleEnd:Clear()
	self.timeTotal = nil
	self.timeAcc = nil
	self:__Clear()
end
return BattleLevelStage_ShowBattleEnd