---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/3/8 15:25

 require "Battle/Logic/Room/Fall/Condition/FallCondition_BeDamageHpPercent"
 require "Battle/Logic/Room/Fall/Condition/FallCondition_HitByActiveSkill"
 require "Battle/Logic/Room/Fall/Condition/FallCondition_AttachElement"
 require "Battle/Logic/Room/Fall/Condition/FallCondition"

-- 枚举
---@type FallCondition[] 枚举映射
FallConditionEnum = {
    ---@type FallCondition 单位生命掉到X%
    OBJECT_HP = FallCondition.New(1, "OBJECT_HP", FallCondition_BeDamageHpPercent.New());
}

-- 枚举映射
---@type FallCondition[] 枚举映射
local fallConditionIdMap = {};

-- 初始化FallCondition映射
for _, value in pairs(FallConditionEnum) do
    fallConditionIdMap[tostring(value:GetId())] = value;
end

-- 根据id获取枚举
---@type function
---@param _id number
---@return FallCondition
function GetFallConditionById(_id)
    return fallConditionIdMap[tostring(_id)]
end