---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/08/20 14:33
--- Describe: 生命周期管理
---

---@class BattleObjCom_LifeCtrl : BattleObjectComponentBase
BattleObjCom_LifeCtrl = class(BattleObjectComponentBase, "BattleObjCom_LifeCtrl")
function BattleObjCom_LifeCtrl:ctor(_data)
	self:__ctor(BattleObjectComponentType.LifeCtrl)
end

---@public
---@param _battleObject BattleObjectBase
---@param _battleCreateUnitParam BattleCreateUnitParam
function BattleObjCom_LifeCtrl:Init(_battleObject, _battleCreateUnitParam)
	self:__Init(_battleObject)
	---@private
	self.__createTime = TimeUtils.battleNow(_battleObject:GetBattleId())
	---@private
	self.__timeAcc = 0
	---@private
	self.__timeTotal = -1
	---@private
	---@type BattleObjCom_Property
	self.__propCom = nil
	---因为自身被替换而死亡
	---@private
	---@type boolean
	self.__replaced = false
	---因为召唤者死亡或被换下而死亡
	---@private
	---@type boolean
	self.__unloaded = false
	---死亡时添加的buff列表
	---@private
	---@type number[]
	self.__deadAddBuffList = {}
	
	--todo: 暂时先只对部分类型进行了处理，将来一点一点把其他类型的都整合进来
	if _battleObject:CheckObjectType(BattleObjectType.Shield) then
		self:__InitShield()
	elseif _battleObject:CheckObjectType(BattleObjectType.SummonedMons) then
		self:__InitSummondMons()
	end
end

---初始化护罩的生命周期参数
---@private
function BattleObjCom_LifeCtrl:__InitShield()
	---@type BattleObjCom_Config
	local _configCom = self:GetObject():GetComponent(BattleObjectComponentType.Config)
	---@type Shield
	local _shieldXls = _configCom:GetInstanceXls()
	self.__timeTotal = _shieldXls.time
	
	self.__propCom = self:GetObject():GetComponent(BattleObjectComponentType.Property)
end

---初始化召唤物的生命周期参数
---@private
function BattleObjCom_LifeCtrl:__InitSummondMons()
	---@type BattleObjCom_Config
	local _configCom = self:GetObject():GetComponent(BattleObjectComponentType.Config)
	---@type SummonedMonster
	local _summondXls = _configCom:GetInstanceXls()
	self.__timeTotal = _summondXls.durationTime
	--for _, _str in pairs(_summondXls.deadBuff) do
	--	table.insert(self.__deadAddBuffList, tonumber(_str))
	--end
	--召唤物的血量死亡由行为树判断
	self.__propCom = nil
end

------------------------------------------------------------------------------------------------------------------------
---检查是否超过生存时间
---@private
function BattleObjCom_LifeCtrl:__CheckTimeOut(_deltaTime)
	--LogTools.LogByLevel(LogLevel.log, "BattleObjCom_LifeCtrl", "__CheckTimeOut", "self.__timeTotal", self.__timeTotal)
	if self.__timeTotal < 0 then return false end
	self.__timeAcc = self.__timeAcc + _deltaTime
	--LogTools.LogByLevel(LogLevel.log, "BattleObjCom_LifeCtrl", "__CheckTimeOut", "self.__timeTotal", self.__timeTotal, "self.__timeAcc", self.__timeAcc)
	return self.__timeAcc > self.__timeTotal
end

---检查是否血量死亡
---@private
function BattleObjCom_LifeCtrl:__CheckHpOver()
	if not self.__propCom then return false end
	return self.__propCom:GetHp() <= 0
end

---检查是否因为自身被替换而死亡
---@private
function BattleObjCom_LifeCtrl:__CheckReplaced()
	return self.__replaced
end

---检查是否因为召唤者死亡或被换下而死亡
---@private
function BattleObjCom_LifeCtrl:__CheckUnloaded()
	return self.__unloaded
end

---@public
function BattleObjCom_LifeCtrl:OnUpdate(_deltaTime)
	
	local _deadType = nil
	if self:__CheckHpOver() then
		_deadType = LuaBehav_Define_DeadType.DeadNormal
	elseif self:__CheckTimeOut(_deltaTime) then
		_deadType = LuaBehav_Define_DeadType.DeadTimeOut
	elseif self:__CheckReplaced() then
		_deadType = LuaBehav_Define_DeadType.DeadSilence
	elseif self:__CheckUnloaded() then
		_deadType = LuaBehav_Define_DeadType.DeadSilence
	else
		return
	end

	---@type BattleObjCom_Buff
	local _buffCom = self:GetObject():GetComponent(BattleObjectComponentType.Buff)
	if _buffCom then
		for i = 1, #self.__deadAddBuffList do
			_buffCom:AddBattleBuffById(self.__deadAddBuffList[i])
		end
	end
	self.battleRoom.battleUnitManager:OnBattleObjectDead(self:GetObject():GetParentUnit():GetNetId(), self:GetObject():GetObjectId(), _deadType)
end

------------------------------------------------------------------------------------------------------------------------

---设置当前生存时间
---@public 
function BattleObjCom_LifeCtrl:ResetLifeTime()
	self.__timeAcc = 0
	---@type BattleUnitCom_TagSelector
	local _tagCom = self:GetObject():GetParentUnit():GetComponent(BattleUnitComponentType.TagSelector)
	_tagCom:SetTag(BattleUnitTagEnum.LifeTimeReset, true)
end

---获取创建时间
---@public
function BattleObjCom_LifeCtrl:GetCreateTime()
	return self.__createTime
end

---设置自身被替换
---@public
function BattleObjCom_LifeCtrl:SetReplaced(_bool)
	self.__replaced = _bool
end

---设置召唤者死亡或被换下而死亡
---@public
function BattleObjCom_LifeCtrl:SetUnloaded(_bool)
	self.__unloaded = _bool
end
------------------------------------------------------------------------------------------------------------------------
---服务器逻辑核生成用于发送给前端逻辑核的全量信息
---@public
function BattleObjCom_LifeCtrl:GetCreateSyncMessage_S2C()
    return self.__createTime
end

---前端逻辑核用服务器发来的全量信息刷新自身数据
---@public
function BattleObjCom_LifeCtrl:OnReceiveCreateSyncMessage_S2C(_createTime)
    self.__createTime = _createTime
end

---前端逻辑核生成用于发送给表现的层全量信息
---@public
function BattleObjCom_LifeCtrl:GetCreateSyncMessage_L2V(_message)
    return nil
end

return BattleObjCom_LifeCtrl