---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/07/12 17:58
--- Describe: 召唤物组件,管理从属关系
---

---@class BattleObjCom_SummonedMons : BattleObjectComponentBase
BattleObjCom_SummonedMons = class(BattleObjectComponentBase, "BattleObjCom_SummonedMons")
function BattleObjCom_SummonedMons:ctor()
	self:__ctor(BattleObjectComponentType.SummonedMons)
end

---@public
---@param _battleObject BattleObjectBase
---@param _battleCreateUnitParam BattleCreateUnitParam
function BattleObjCom_SummonedMons:Init(_battleObject, _battleCreateUnitParam)
	self:__Init(_battleObject)
	self.__subordinateNetId = _battleCreateUnitParam.subordinateNetId
	self.__subordinateObjId = _battleCreateUnitParam.subordinateObjId
end

---获取召唤者的netId
---@public
---@return number
function BattleObjCom_SummonedMons:GetSubordinateNetId()
	return self.__subordinateNetId
end

---获取召唤者的objId
---@public
---@return number 
function BattleObjCom_SummonedMons:GetSubordinateObjId()
	return self.__subordinateObjId
end

---获取召唤者的unit，不是当前组件所属的unit
---@public
---@return BattleUnitBase
function BattleObjCom_SummonedMons:GetSubordinateUnit()
	return self.battleRoom.battleUnitManager:GetUnit(self.__subordinateNetId)
end

---获取召唤者的object, 不是当前组件所属的object
---@public
---@return BattleObjectBase
function BattleObjCom_SummonedMons:GetSubordinateObject()
	return self.battleRoom.battleObjectManager:GetObject(self.__subordinateObjId)
end

---获取召唤者unit身上的组件
---@public
---@param _battleUnitComponentType BattleUnitComponentType
---@return BattleUnitComponentBase
function BattleObjCom_SummonedMons:GetSubordinateUnitComponent(_battleUnitComponentType)
	local _unit = self:GetSubordinateUnit()
	return _unit and _unit:GetComponent(_battleUnitComponentType)
end

---获取召唤者object身上的组件
---@public
---@param _battleObjectComponentType BattleObjectComponentType
---@return BattleObjectComponentBase
function BattleObjCom_SummonedMons:GetSubordinateObjectComponent(_battleObjectComponentType)
	local _obj = self:GetSubordinateObject()
	return _obj and _obj:GetComponent(_battleObjectComponentType)
end

---@public
function BattleObjCom_SummonedMons:Clear()
	self.__subordinateNetId = nil
	self.__subordinateObjId = nil
	self:__Clear()
end

return BattleObjCom_SummonedMons