---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/4/13 11:13

require "Battle/Logic/Room/BattleType/MainLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/TrainLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/TrainMultiLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/TowerLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/BountyLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/WeaponLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/LimitedTimeLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/MultiPveBossLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/PatrolLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/TrialRoleLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/SmallBattleGroundLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/GuildWarLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/AbyssFrontLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/RogueLevel_BattleTypeOper"
require "Battle/Logic/Room/BattleType/BattleType"


-- 枚举
---@class BattleTypeEnum:table
---@type BattleType[] 枚举映射
BattleTypeEnum = {
    ---@type BattleType 主线关卡
    MAIN_LEVEL = BattleType.New(1, MainLevel_BattleTypeOper.New());
    ---@type BattleType 训练关卡
    TRAIN_LEVEL = BattleType.New(2, TrainLevel_BattleTypeOper.New());
    ---@type BattleType 多人训练关卡
    TRAIN_MULTI_LEVEL = BattleType.New(3, TrainMultiLevel_BattleTypeOper.New());
    ---@type BattleType 爬塔关卡
    TOWER_LEVEL = BattleType.New(5, TowerLevel_BattleTypeOper.New());
    ---@type BattleType 悬赏关卡
    BOUNTY_LEVEL = BattleType.New(6, BountyLevel_BattleTypeOper.New());
    ---@type BattleType 武器关卡
    WEAPON_LEVEL = BattleType.New(7, WeaponLevel_BattleTypeOper.New());
    ---@type BattleType 限时关卡
    LIMITED_TIME_LEVEL = BattleType.New(8, LimitedTimeLevel_BattleTypeOper.New());
    ---@type BattleType 多人boss pve关卡
    MULTI_PVE_BOSS_LEVEL = BattleType.New(9, MultiPveBossLevel_BattleTypeOper.New());
    ---@type BattleType 乌拉拉关卡
    PATROL_LEVEL = BattleType.New(10, PatrolLevel_BattleTypeOper.New());
    ---@type BattleType 试用关卡
    TRIALROLE_LEVEL = BattleType.New(11, TrialRoleLevel_BattleTypeOper.New());
    ---@type BattleType 小战场
    SMALL_BATTLE_GROUND_LEVEL = BattleType.New(12, SmallBattleGroundLevel_BattleTypeOper.New());
    ---@type BattleType 大战场
    ABYSS_FRONT_LEVEL = BattleType.New(13, AbyssFrontLevel_BattleTypeOper.New());
    ---@type BattleType 团本
    GUILD_WAR_LEVEL = BattleType.New(14, GuildWarLevel_BattleTypeOper.New());
    ---@type BattleType Rogue关卡
    ROGUE_LEVEL = BattleType.New(15, RogueLevel_BattleTypeOper.New());
}

-- 枚举映射
---@type BattleType[] 枚举映射
local battleTypeIdMap = {};

-- 初始化BattleType映射
for _, value in pairs(BattleTypeEnum) do
    battleTypeIdMap[tostring(value:GetId())] = value;
end

-- 根据id获取枚举
---@type function
---@param _id number
---@return BattleType
function GetBattleTypeById(_id)
    return battleTypeIdMap[tostring(_id)]
end