---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jiangxuechen
--- DateTime: 2022/11/05 15:52
--- Describe: 基础对象池
---

require "Battle/Utils/PoolObj/Utils_BasePoolData"

---@class Utils_BasePool : table
Utils_BasePool = class(nil, "Utils_BasePool")
function Utils_BasePool:ctor(_data) end

---@public
function Utils_BasePool:Init(_dataType, _initNum, _expandStep)
	---@private
	---@type Utils_BasePoolData[]
	self.__deadList = {}
	---@private
	self.__dataType = _dataType
	self.__ExpandStep = _expandStep or 10
	self:__Expand(_initNum or 10)
end

---@private
function Utils_BasePool:__Expand(_expandNum)
	local _func = self.__dataType.New
	local _deadList = self.__deadList
	for i = 1, _expandNum do
		table.insert(_deadList, _func())
	end
end

---@public
---@return Utils_BasePoolData
function Utils_BasePool:Pop()
	local _max = #self.__deadList
	if 0 == _max then
		self:__Expand(self.__ExpandStep)
		_max = #self.__deadList
	end
	local _ret = self.__deadList[_max]
	table.remove(self.__deadList, _max)
	return _ret
end

---@public
---@param _poolData Utils_BasePoolData
function Utils_BasePool:Push(_poolData)
	_poolData:OnPush()
	table.insert(self.__deadList, _poolData)
end

---@public
function Utils_BasePool:Clear()
	for _, _poolData in pairs(self.__deadList) do
		_poolData:Clear()
	end
	self.__deadList = nil
	self.__ExpandStep = nil
end

return Utils_BasePool