local default = {id=0,scene="",soundEventName="",voxelData3="",meshVoxelForDebug="",victoryShowPosition=xlsNilTable,victoryShowRotation=xlsNilTable,boundary="",weatherID=0,postprocess="",border=""}
local mt = {}
mt.__index = function(table, key)
    local val = rawget(table, key)
    if val then
        return val
    else
        return default[key]
    end
end
---@class BattleScene_Xls : table 
BattleScene_Xls =
{
    ["1"]=setmetatable({id=1,scene="CommonSky_light_01",soundEventName="Amb_CommonSky_Light",voxelData3="voxelData_CommonSky_light_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=200,[3]=0},victoryShowRotation={[1]=12,[2]=-65,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["2"]=setmetatable({id=2,scene="CommonSky_light_01",soundEventName="Amb_CommonSky_Light",voxelData3="voxelData_CommonSky_light_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-25,[2]=0,[3]=0},victoryShowRotation={[1]=14,[2]=153,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["3"]=setmetatable({id=3,scene="CommonSky_light_01",soundEventName="Amb_CommonSky_Light",voxelData3="voxelData_CommonSky_light_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-25,[2]=0,[3]=0},victoryShowRotation={[1]=14,[2]=105,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["4"]=setmetatable({id=4,scene="CommonSky_night_01",soundEventName="Amb_CommonSky_Dusk",voxelData3="voxelData_CommonSky_night_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=38,[3]=0},victoryShowRotation={[1]=11,[2]=-90,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["5"]=setmetatable({id=5,scene="CommonSky_night_01",soundEventName="Amb_CommonSky_Dusk",voxelData3="voxelData_CommonSky_night_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=38,[3]=0},victoryShowRotation={[1]=11,[2]=-120,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["6"]=setmetatable({id=6,scene="CommonSky_ dusk_01",soundEventName="Amb_CommonSky_Dusk",voxelData3="voxelData_CommonSky_ dusk_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=-14,[3]=0},victoryShowRotation={[1]=14,[2]=180,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["7"]=setmetatable({id=7,scene="CommonSky_ dusk_01",soundEventName="Amb_CommonSky_Dusk",voxelData3="voxelData_CommonSky_ dusk_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=6,[2]=-104,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["8"]=setmetatable({id=8,scene="CommonSky_light_Relic_01",soundEventName="Amb_CommonSky_Light",voxelData3="voxelData_CommonSky_light_Relic_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=-30,[3]=0},victoryShowRotation={[1]=14,[2]=105,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["9"]=setmetatable({id=9,scene="CommonSky_ dusk_Relic_01",soundEventName="Amb_CommonSky_Dusk",voxelData3="voxelData_CommonSky_night_01_PerformanceTestEmptyVoxel_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="Commonsky_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["100"]=setmetatable({id=100,scene="Scenes_WundeRend",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["101"]=setmetatable({id=101,scene="Scenes_WundeRend_Day_Low_fly",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Day_Low_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["102"]=setmetatable({id=102,scene="Scenes_WundeRend_Day_Mid_fly",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Day_Mid_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["103"]=setmetatable({id=103,scene="Scenes_WundeRend_Daybad",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Daybad_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["104"]=setmetatable({id=104,scene="Scenes_WundeRend_Daybad_Low_fly",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Daybad_Low_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["105"]=setmetatable({id=105,scene="Scenes_WundeRend_Daybad_Mid_fly",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Daybad_Mid_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["110"]=setmetatable({id=110,scene="Scenes_WundeRend_dusk",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_dusk_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["111"]=setmetatable({id=111,scene="Scenes_WundeRend_dusk_Low_fly",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_dusk_Low_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["112"]=setmetatable({id=112,scene="Scenes_WundeRend_dusk_Mid_fly",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_dusk_Mid_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["113"]=setmetatable({id=113,scene="Scenes_WundeRend_duskbad",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_duskbad_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["114"]=setmetatable({id=114,scene="Scenes_WundeRend_duskbad_Low_fly",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_duskbad_Low_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["115"]=setmetatable({id=115,scene="Scenes_WundeRend_duskbad_Mid_fly",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_duskbad_Mid_fly_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["116"]=setmetatable({id=116,scene="Scenes_WundeRend_duskbad_Low_fly_01",soundEventName="Amb_WundeRend_Dusk",voxelData3="voxelData_Scenes_WundeRend_duskbad_Low_fly_011_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["191"]=setmetatable({id=191,scene="Scenes_WundeRend_Rainbad",soundEventName="Amb_WundeRend_Light",voxelData3="voxelData_Scenes_WundeRend_Rainbad_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-68,[2]=531,[3]=0},victoryShowRotation={[1]=-9.9,[2]=-95,[3]=0},boundary="Wunderend_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["201"]=setmetatable({id=201,scene="Cave_pipeline_02",soundEventName="Amb_Cave_Dark",voxelData3="voxelData_Cave_pipeline_021_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=2,[2]=389,[3]=19},victoryShowRotation={[1]=9,[2]=35,[3]=0},boundary="Cave_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["202"]=setmetatable({id=202,scene="Scene_Bogaland",soundEventName="Amb_Bogaland_Light",voxelData3="voxelData_Scene_Bogaland_Test_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=32,[2]=79,[3]=340},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="Bogaland_Collider_Test",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["203"]=setmetatable({id=203,scene="Scene_Bogaland_02",soundEventName="Amb_Bogaland_Light",voxelData3="voxelData_Scene_Bogaland_Test_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=32,[2]=79,[3]=340},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="Bogaland_Collider_Test",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["204"]=setmetatable({id=204,scene="Scene_Bogaland_dusk",soundEventName="Amb_Bogaland_Dusk",voxelData3="voxelData_Scene_Bogaland_Test_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=80,[2]=80,[3]=420},victoryShowRotation={[1]=0,[2]=40,[3]=0},boundary="Bogaland_Collider_Test",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["205"]=setmetatable({id=205,scene="Cave_pipeline_02",soundEventName="Amb_Cave_Dark",voxelData3="voxelData_Cave_pipeline_021_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=2,[2]=389,[3]=19},victoryShowRotation={[1]=9,[2]=35,[3]=0},boundary="Cave_Collision_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["301"]=setmetatable({id=301,scene="Scenes_Bojialande_vestige",soundEventName="Amb_BojialandeVestige_Dark",voxelData3="voxelData_Scenes_Bojialande_vestige_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=133,[2]=66,[3]=74},victoryShowRotation={[1]=0,[2]=44,[3]=0},boundary="Bojialande_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["302"]=setmetatable({id=302,scene="Scenes_Bojialande_vestige_Rema_01",soundEventName="Amb_BojialandeVestige_Dark",voxelData3="voxelData_Scenes_Bojialande_vestige_Rema_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=100},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="Bojialande_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["303"]=setmetatable({id=303,scene="Scenes_Towerclimbing_01",soundEventName="Amb_BojialandeVestige_Dark",voxelData3="voxelData_Scenes_Towerclimbing_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=100},victoryShowRotation={[1]=0,[2]=180,[3]=0},boundary="Bojialande_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["304"]=setmetatable({id=304,scene="Scenes_Bojialande_vestige",soundEventName="Amb_BojialandeVestige_Dark",voxelData3="voxelData_Scenes_Bojialande_vestige_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=133,[2]=66,[3]=74},victoryShowRotation={[1]=0,[2]=44,[3]=0},boundary="bojialande_vestige_boss",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["320"]=setmetatable({id=320,scene="Scene_Bcastle",soundEventName="Amb_Bcastle_Dusk",voxelData3="voxelData_Scene_Bcastle1_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=136,[2]=5,[3]=781},victoryShowRotation={[1]=0,[2]=20,[3]=0},boundary="BcastleCollision1"},mt),
    ["401"]=setmetatable({id=401,scene="Scenes_SnowMountain",soundEventName="Amb_SnowMountain_Light",voxelData3="voxelData_Scenes_SnowMountain_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=600,[3]=0},victoryShowRotation={[1]=15,[2]=-70,[3]=0},boundary="SnowMountain_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["402"]=setmetatable({id=402,scene="Scenes_SnowMountain_Morning",soundEventName="Amb_SnowMountain_Light",voxelData3="voxelData_Scenes_SnowMountain_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=600,[3]=0},victoryShowRotation={[1]=15,[2]=-70,[3]=0},boundary="SnowMountain_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["403"]=setmetatable({id=403,scene="Scenes_SnowMountainMove",soundEventName="Amb_SnowMountain_Light_Storm",voxelData3="voxelData_Scenes_SnowMountain_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=600,[3]=0},victoryShowRotation={[1]=15,[2]=-70,[3]=0},boundary="Boundless_Collider",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["404"]=setmetatable({id=404,scene="Scenes_SnowMountain_Day",soundEventName="Amb_SnowMountain_Light",voxelData3="voxelData_Scenes_SnowMountain_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=600,[3]=0},victoryShowRotation={[1]=15,[2]=-70,[3]=0},boundary="SnowMountain_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["405"]=setmetatable({id=405,scene="Scenes_SnowMountain_Dusk",soundEventName="Amb_SnowMountain_Light",voxelData3="voxelData_Scenes_SnowMountain_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=600,[3]=0},victoryShowRotation={[1]=15,[2]=-70,[3]=0},boundary="SnowMountain_Collider_Reg",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["501"]=setmetatable({id=501,scene="Scenes_Ice_aurora_front",soundEventName="Amb_IceAurora_Light",voxelData3="voxelData_Scenes_Ice_aurora_front1_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=110,[3]=-250},victoryShowRotation={[1]=-5,[2]=-175,[3]=0},boundary="Scenes_Ice_aurora_front",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["502"]=setmetatable({id=502,scene="Scenes_Ice_aurora_front",soundEventName="Amb_IceAurora_Light",voxelData3="voxelData_Scenes_Ice_aurora_front1_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=110,[3]=-250},victoryShowRotation={[1]=-5,[2]=-175,[3]=0},boundary="Scenes_Ice_aurora_front",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["601"]=setmetatable({id=601,scene="Scenes_Desert_2",soundEventName="Amb_Desert_Dusk",voxelData3="voxelData_Scenes_Desert_2602_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-34,[2]=130,[3]=1},victoryShowRotation={[1]=0,[2]=17,[3]=1},boundary="602Collision",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["602"]=setmetatable({id=602,scene="Scenes_Desert_2",soundEventName="Amb_Desert_Dusk",voxelData3="voxelData_Scenes_Desert_2602_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-34,[2]=130,[3]=0},victoryShowRotation={[1]=0,[2]=17,[3]=0},boundary="602Collision"},mt),
    ["603"]=setmetatable({id=603,scene="Scenes_Desertnew",soundEventName="Amb_Desert_Dusk",voxelData3="voxelData_Scenes_Desertnew603_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=560,[2]=300,[3]=645},victoryShowRotation={[1]=15,[2]=16,[3]=0},boundary="Collision602"},mt),
    ["8001"]=setmetatable({id=8001,scene="Scenes_Activity_Fantasy",soundEventName="",voxelData3="voxelData_Scenes_Activity_Fantasy1_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-130,[2]=129,[3]=-400},victoryShowRotation={[1]=3,[2]=-134,[3]=0},boundary="Scenes_Activity_Fantasy",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["8002"]=setmetatable({id=8002,scene="Scenes_Activity_Fantasy_Boss",soundEventName="",voxelData3="voxelData_Scenes_Activity_Fantasy1_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-35,[2]=119,[3]=-446},victoryShowRotation={[1]=0,[2]=-140,[3]=0},boundary="Boundless_Collider",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["9903"]=setmetatable({id=9903,scene="Cave_pipeline",soundEventName="",voxelData3="voxelData_Cave_pipeline_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=-939.3,[2]=572,[3]=1979.9},victoryShowRotation={[1]=0,[2]=-195.6,[3]=0},boundary="Boundless_Collider",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["9904"]=setmetatable({id=9904,scene="CommonSky_light_01",soundEventName="",voxelData3="voxelData_CommonSky_night_01_PerformanceTestEmptyVoxel_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=100,[3]=0},boundary="Boundless_Collider",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["9905"]=setmetatable({id=9905,scene="Battle_Test_tubularBattleScene_1",soundEventName="",voxelData3="voxelData_Scenes_WundeRend_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="Wunderend_Collision_Reg"},mt),
    ["9906"]=setmetatable({id=9906,scene="CommonSky_light_01",soundEventName="",voxelData3="voxelData_CommonSky_light_02_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=100,[3]=0},boundary="tafangceshi",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
    ["9007"]=setmetatable({id=9007,scene="CommonSky_light_01",soundEventName="",voxelData3="voxelData_CommonSky_light_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="CPlaneTest_000",weatherID=0,postprocess="",border="PF_BattleAirWall_Scrap"},mt),
    ["9008"]=setmetatable({id=9008,scene="CommonSky_light_01",soundEventName="",voxelData3="voxelData_CommonSky_light_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="CPlaneTest_001",weatherID=0,postprocess="",border="PF_BattleAirWall_Scrap"},mt),
    ["9009"]=setmetatable({id=9009,scene="CommonSky_light_01",soundEventName="",voxelData3="voxelData_CommonSky_light_01_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=0,[2]=0,[3]=0},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="CPlaneTest_002",weatherID=0,postprocess="",border="PF_BattleAirWall_Scrap"},mt),
    ["4000101"]=setmetatable({id=4000101,scene="Scenes_SnowMountain",soundEventName="",voxelData3="voxelData_Scenes_SnowMountain_Reg_size3_mode1",meshVoxelForDebug="",victoryShowPosition={[1]=300600192},victoryShowRotation={[1]=0,[2]=0,[3]=0},boundary="SnowMountain_Ankang",weatherID=0,postprocess="",border="PF_BattleAirWall_Ball"},mt),
}
--生成获取数据的方法
---@return BattleScene
function GetBattleSceneData(id)
    return BattleScene_Xls[tostring(id)]
end
--自动生成注释
---@class BattleScene : table 
---@field id number
---@field scene string
---@field soundEventName string
---@field voxelData3 string
---@field meshVoxelForDebug string
---@field victoryShowPosition table
---@field victoryShowRotation table
---@field boundary string
---@field weatherID number
---@field postprocess string
---@field border string
