local default = {id=0,chapterType=0,chapterIndex=0,regionId=0,isShow=0,chapterList=0,chapterName="",chapterInfo="",chapterInfoEn="",chapterStory="",chapterConditionId=xlsNilTable,unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="",chapterPictureWoman="",startPicMan="",startPicWoman="",iosDefaultValue=0}
local mt = {}
mt.__index = function(table, key)
    local val = rawget(table, key)
    if val then
        return val
    else
        return default[key]
    end
end
---@class MainChapter_Xls : table 
MainChapter_Xls =
{
    ["99"]=setmetatable({id=99,chapterType=1,chapterIndex=0,regionId=0,isShow=0,chapterList=0,chapterName="序章",chapterInfo="信标",chapterInfoEn="CHAPTER ZERO",chapterStory="湛蓝的天空中，神秘的舰船上，危机同时来袭。",chapterConditionId={[1]=101},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter01",chapterPic="tujian_chapter01_bg",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["100"]=setmetatable({id=100,chapterType=1,chapterIndex=0,regionId=1001,isShow=0,chapterList=0,chapterName="序章",chapterInfo="预言",chapterInfoEn="CHAPTER ZERO",chapterStory="湛蓝的天空中，神秘的舰船上，危机同时来袭。",chapterConditionId={[1]=101},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter01",chapterPic="tujian_chapter01_bg",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["101"]=setmetatable({id=101,chapterType=1,chapterIndex=1,regionId=1001,isShow=1,chapterList=1,chapterName="第一章",chapterInfo="新的起点",chapterInfoEn="CHAPTER ONE",chapterStory="人终究会在过去的裹挟下，走向宿命，走向未来。",chapterConditionId={[1]=101},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter02",chapterPic="tujian_chapter02_bg",chapterPicture="bg-cp1-new-man",startVideo="ChapterOne_Start",startStory=0,landmarkId=1011,startPic="UIWorldMap_Sprite_xintu",chapterPictureMan="bg-cp1-new-man",chapterPictureWoman="bg-cp1-new-woman",startPicMan="UIWorldMap_Sprite_xintu",startPicWoman="UIWorldMap_Sprite_xintu_woman"},mt),
    ["102"]=setmetatable({id=102,chapterType=1,chapterIndex=2,regionId=1001,isShow=1,chapterList=1,chapterName="第二章",chapterInfo="天将倾覆，人归何处",chapterInfoEn="CHAPTER TWO",chapterStory="被尊为“神圣”的巨大遗迹缓缓下落，人类将逃亡何方。",chapterConditionId={[1]=6101112},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter03",chapterPic="tujian_chapter03_bg",chapterPicture="bg-cp2",startVideo="",startStory=102010,landmarkId=1021,startPic="UIWorldMap_Sprite_tu2",chapterPictureMan="bg-cp2",chapterPictureWoman="bg-cp2",startPicMan="UIWorldMap_Sprite_tu2",startPicWoman="UIWorldMap_Sprite_tu2"},mt),
    ["103"]=setmetatable({id=103,chapterType=1,chapterIndex=3,regionId=1001,isShow=1,chapterList=1,chapterName="第三章",chapterInfo="秘境追想",chapterInfoEn="CHAPTER THREE",chapterStory="遗迹中潜藏着危机，各种思绪在此处交织。",chapterConditionId={[1]=6102113},unlockLevel=23,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter04",chapterPic="tujian_chapter04_bg",chapterPicture="bg-cp3",startVideo="ChapterStart",startStory=3010,landmarkId=1031,startPic="UIWorldMap_Sprite_tu3",chapterPictureMan="bg-cp3",chapterPictureWoman="bg-cp3",startPicMan="UIWorldMap_Sprite_tu3",startPicWoman="UIWorldMap_Sprite_tu3"},mt),
    ["104"]=setmetatable({id=104,chapterType=1,chapterIndex=4,regionId=1001,isShow=1,chapterList=1,chapterName="第四章",chapterInfo="滞锁极境",chapterInfoEn="CHAPTER FOUR",chapterStory="风雪席卷的拉普兰地区，异常在逐渐蔓延。",chapterConditionId={[1]=6103112},unlockLevel=26,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp4",startVideo="ChapterStart",startStory=4000,landmarkId=1041,startPic="UIWorldMap_Sprite_tu4",chapterPictureMan="bg-cp4",chapterPictureWoman="bg-cp4",startPicMan="UIWorldMap_Sprite_tu4",startPicWoman="UIWorldMap_Sprite_tu4"},mt),
    ["105"]=setmetatable({id=105,chapterType=1,chapterIndex=5,regionId=1001,isShow=1,chapterList=1,chapterName="第五章",chapterInfo="虔诚之拥",chapterInfoEn="CHAPTER FIVE",chapterStory="你为什么而来。",chapterConditionId={[1]=6104113},unlockLevel=30,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp5",startVideo="ChapterStart",startStory=5000,landmarkId=1051,startPic="UIWorldMap_Sprite_tu5",chapterPictureMan="bg-cp5",chapterPictureWoman="bg-cp5",startPicMan="UIWorldMap_Sprite_tu5",startPicWoman="UIWorldMap_Sprite_tu5"},mt),
    ["106"]=setmetatable({id=106,chapterType=1,chapterIndex=6,regionId=1001,isShow=1,chapterList=1,chapterName="第六章",chapterInfo="终天恩怨",chapterInfoEn="CHAPTER SIX",chapterStory="邂逅。陪伴。抉择。背叛。",chapterConditionId={[1]=6105113},unlockLevel=33,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp6",startVideo="ChapterStart",startStory=6010,landmarkId=1061,startPic="UIWorldMap_Sprite_tu6",chapterPictureMan="bg-cp6",chapterPictureWoman="bg-cp6",startPicMan="UIWorldMap_Sprite_tu6",startPicWoman="UIWorldMap_Sprite_tu6",iosDefaultValue=1},mt),
    ["107"]=setmetatable({id=107,chapterType=1,chapterIndex=7,regionId=1001,isShow=1,chapterList=1,chapterName="第七章",chapterInfo="沙丘之上",chapterInfoEn="CHAPTER SEVEN",chapterStory="你中有我，我中有你。",chapterConditionId={[1]=6106110},unlockLevel=36,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp7",startVideo="ChapterStart",startStory=7000,landmarkId=1071,startPic="UIWorldMap_Sprite_tu7",chapterPictureMan="bg-cp7",chapterPictureWoman="bg-cp7",startPicMan="UIWorldMap_Sprite_tu7",startPicWoman="UIWorldMap_Sprite_tu7",iosDefaultValue=1},mt),
    ["108"]=setmetatable({id=108,chapterType=1,chapterIndex=8,regionId=1001,isShow=1,chapterList=1,chapterName="第八章",chapterInfo="凝夜咏叹",chapterInfoEn="CHAPTER EIGHT",chapterStory="雾中之镜，不见真形。",chapterConditionId={[1]=6107111},unlockLevel=40,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp8",startVideo="ChapterStart",startStory=0,landmarkId=1081,startPic="UIWorldMap_Sprite_tu8",chapterPictureMan="bg-cp8",chapterPictureWoman="bg-cp8",startPicMan="UIWorldMap_Sprite_tu8",startPicWoman="UIWorldMap_Sprite_tu8",iosDefaultValue=1},mt),
    ["201"]=setmetatable({id=201,chapterType=2,chapterIndex=1,regionId=1001,isShow=1,chapterList=0,chapterName="第一章",chapterInfo="新的起点",chapterInfoEn="CHAPTER ONE",chapterStory="人终究会在过去的裹挟下，走向宿命，走向未来。",chapterConditionId={[1]=6102113},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter02",chapterPic="tujian_chapter02_bg",chapterPicture="bg-cp1-new-man",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="bg-cp1-new-man",chapterPictureWoman="bg-cp1-new-woman"},mt),
    ["202"]=setmetatable({id=202,chapterType=2,chapterIndex=2,regionId=1001,isShow=1,chapterList=0,chapterName="第二章",chapterInfo="天将倾覆，人归何处",chapterInfoEn="CHAPTER TWO",chapterStory="被尊为“神圣”的巨大遗迹缓缓下落，人类将逃亡何方。",chapterConditionId={[1]=6102113},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter03",chapterPic="tujian_chapter03_bg",chapterPicture="bg-cp2",startVideo="",startStory=102010,landmarkId=0,startPic="",chapterPictureMan="bg-cp2",chapterPictureWoman="bg-cp2"},mt),
    ["203"]=setmetatable({id=203,chapterType=2,chapterIndex=3,regionId=1001,isShow=1,chapterList=0,chapterName="第三章",chapterInfo="秘境追想",chapterInfoEn="CHAPTER THREE",chapterStory="遗迹中潜藏着危机，各种思绪在此处交织。",chapterConditionId={[1]=6103112},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter04",chapterPic="tujian_chapter04_bg",chapterPicture="bg-cp3",startVideo="",startStory=3010,landmarkId=0,startPic="",chapterPictureMan="bg-cp3",chapterPictureWoman="bg-cp3"},mt),
    ["204"]=setmetatable({id=204,chapterType=2,chapterIndex=4,regionId=1001,isShow=1,chapterList=0,chapterName="第四章",chapterInfo="滞锁极境",chapterInfoEn="CHAPTER FOUR",chapterStory="风雪席卷的拉普兰地区，异常在逐渐蔓延。",chapterConditionId={[1]=6104113},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp4",startVideo="",startStory=4000,landmarkId=0,startPic="",chapterPictureMan="bg-cp4",chapterPictureWoman="bg-cp4"},mt),
    ["205"]=setmetatable({id=205,chapterType=2,chapterIndex=5,regionId=1001,isShow=1,chapterList=0,chapterName="第五章",chapterInfo="虔诚之拥",chapterInfoEn="CHAPTER FIVE",chapterStory="你为什么而来。",chapterConditionId={[1]=6105113},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp5",startVideo="",startStory=5000,landmarkId=0,startPic="",chapterPictureMan="bg-cp5",chapterPictureWoman="bg-cp5"},mt),
    ["206"]=setmetatable({id=206,chapterType=2,chapterIndex=6,regionId=1001,isShow=1,chapterList=0,chapterName="第六章",chapterInfo="终天恩怨",chapterInfoEn="CHAPTER SIX",chapterStory="邂逅。陪伴。抉择。背叛。",chapterConditionId={[1]=6106110},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp6",startVideo="",startStory=6010,landmarkId=0,startPic="",chapterPictureMan="bg-cp6",chapterPictureWoman="bg-cp6",startPicMan="",startPicWoman="",iosDefaultValue=1},mt),
    ["207"]=setmetatable({id=207,chapterType=2,chapterIndex=7,regionId=1001,isShow=1,chapterList=0,chapterName="第七章",chapterInfo="沙丘之上",chapterInfoEn="CHAPTER SEVEN",chapterStory="你中有我，我中有你。",chapterConditionId={[1]=6107111},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp7",startVideo="",startStory=7000,landmarkId=0,startPic="",chapterPictureMan="bg-cp7",chapterPictureWoman="bg-cp7",startPicMan="",startPicWoman="",iosDefaultValue=1},mt),
    ["208"]=setmetatable({id=208,chapterType=2,chapterIndex=8,regionId=1001,isShow=1,chapterList=0,chapterName="第八章",chapterInfo="凝夜咏叹",chapterInfoEn="CHAPTER EIGHT",chapterStory="雾中之镜，不见真形。",chapterConditionId={[1]=6108111},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="tujian_chapter05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-cp8",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="bg-cp7",chapterPictureWoman="bg-cp7",startPicMan="",startPicWoman="",iosDefaultValue=1},mt),
    ["498"]=setmetatable({id=498,chapterType=4,chapterIndex=98,regionId=1001,isShow=0,chapterList=0,chapterName="法尼娅",chapterInfo="Faroli",chapterInfoEn="Faroli",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=401,[2]=405,[3]=6104101},unlockLevel=32,chapterBgTex="checkpoint_faluli_bg",chapterIcon="Faluli_128_128",chaperColleIcon="tujian_juqing_faluli",chapterPic="tujian_leader01",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["497"]=setmetatable({id=497,chapterType=4,chapterIndex=97,regionId=1001,isShow=0,chapterList=0,chapterName="奈纳",chapterInfo="涂鸦绘本",chapterInfoEn="Naina",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=6102107},unlockLevel=0,chapterBgTex="checkpoint_naina_bg",chapterIcon="Naina_128_128",chaperColleIcon="tujian_juqing_pic05",chapterPic="tujian_chapter05_bg",chapterPicture="bg-naina",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="bg-naina",chapterPictureWoman="bg-naina"},mt),
    ["496"]=setmetatable({id=496,chapterType=4,chapterIndex=96,regionId=1001,isShow=0,chapterList=0,chapterName="夏洛",chapterInfo="雪山巅的演奏会",chapterInfoEn="Charlotte",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=6104107},unlockLevel=0,chapterBgTex="checkpoint_role_bg",chapterIcon="Xialuo_128_128",chaperColleIcon="tujian_juqing_waxiti",chapterPic="tujian_chapter03_bg",chapterPicture="bg-xialuo",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="bg-xialuo",chapterPictureWoman="bg-xialuo"},mt),
    ["495"]=setmetatable({id=495,chapterType=4,chapterIndex=95,regionId=1001,isShow=0,chapterList=0,chapterName="维拉",chapterInfo="Weila",chapterInfoEn="Charlotte",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=101,[2]=20020},unlockLevel=0,chapterBgTex="checkpoint_role_bg",chapterIcon="Xialuo_128_128",chaperColleIcon="tujian_juqing_waxiti",chapterPic="tujian_chapter03_bg",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["494"]=setmetatable({id=494,chapterType=4,chapterIndex=94,regionId=1001,isShow=0,chapterList=0,chapterName="瓦希缇",chapterInfo="Vashti",chapterInfoEn="Charlotte",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=402,[2]=405,[3]=6104101},unlockLevel=33,chapterBgTex="checkpoint_role_bg",chapterIcon="Xialuo_128_128",chaperColleIcon="tujian_juqing_waxiti",chapterPic="tujian_chapter03_bg",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["301"]=setmetatable({id=301,chapterType=3,chapterIndex=1,regionId=1001,isShow=0,chapterList=0,chapterName="偏折实验",chapterInfo="大量通用币产出",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["302"]=setmetatable({id=302,chapterType=3,chapterIndex=2,regionId=1001,isShow=0,chapterList=0,chapterName="负荷模拟",chapterInfo="大量角色经验产出",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["303"]=setmetatable({id=303,chapterType=3,chapterIndex=3,regionId=1001,isShow=0,chapterList=0,chapterName="损害演算",chapterInfo="大量武装经验产出",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["304"]=setmetatable({id=304,chapterType=3,chapterIndex=4,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划α",chapterInfo="镜像01",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["305"]=setmetatable({id=305,chapterType=3,chapterIndex=5,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划β",chapterInfo="镜像02",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["306"]=setmetatable({id=306,chapterType=3,chapterIndex=6,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划γ",chapterInfo="镜像03",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["307"]=setmetatable({id=307,chapterType=3,chapterIndex=7,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划δ",chapterInfo="镜像04",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["308"]=setmetatable({id=308,chapterType=3,chapterIndex=8,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划ε",chapterInfo="镜像05",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["309"]=setmetatable({id=309,chapterType=3,chapterIndex=9,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划ζ",chapterInfo="镜像06",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["310"]=setmetatable({id=310,chapterType=3,chapterIndex=10,regionId=1001,isShow=0,chapterList=0,chapterName="清算规划η",chapterInfo="镜像07",chapterInfoEn="",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=103},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["299"]=setmetatable({id=299,chapterType=2,chapterIndex=99,regionId=1001,isShow=1,chapterList=0,chapterName="验证与训练关卡",chapterInfo="特殊玩法",chapterInfoEn="confirmation",chapterStory="力量来自于内心的强大。 ——贝宁",chapterConditionId={[1]=101},unlockLevel=0,chapterBgTex="ziyuanguan_bg",chapterIcon="",chaperColleIcon="tujian_chapter01",chapterPic="tujian_chapter01_bg",chapterPicture="UILevelList_Texture_bg",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="UILevelList_Texture_bg",chapterPictureWoman="UILevelList_Texture_bg"},mt),
    ["480"]=setmetatable({id=480,chapterType=6,chapterIndex=80,regionId=1001,isShow=0,chapterList=0,chapterName="教学关",chapterInfo="教学关",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=1}},mt),
    ["481"]=setmetatable({id=481,chapterType=6,chapterIndex=1,regionId=1001,isShow=0,chapterList=0,chapterName="武装支线1",chapterInfo="武装支线1",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=6102101},unlockLevel=18},mt),
    ["482"]=setmetatable({id=482,chapterType=6,chapterIndex=2,regionId=1001,isShow=0,chapterList=0,chapterName="武装支线2",chapterInfo="武装支线2",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=6102101},unlockLevel=19},mt),
    ["483"]=setmetatable({id=483,chapterType=6,chapterIndex=3,regionId=1001,isShow=0,chapterList=0,chapterName="武装支线3",chapterInfo="武装支线3",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=6104101},unlockLevel=32},mt),
    ["484"]=setmetatable({id=484,chapterType=6,chapterIndex=4,regionId=1001,isShow=0,chapterList=0,chapterName="武装支线4",chapterInfo="武装支线4",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=6104101},unlockLevel=38},mt),
    ["485"]=setmetatable({id=485,chapterType=6,chapterIndex=5,regionId=1001,isShow=0,chapterList=0,chapterName="武装支线5",chapterInfo="武装支线5",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=6104101},unlockLevel=38},mt),
    ["470"]=setmetatable({id=470,chapterType=2,chapterIndex=10,regionId=1001,isShow=0,chapterList=0,chapterName="挑战关第一阶段",chapterInfo="挑战关第一阶段",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=16103104}},mt),
    ["471"]=setmetatable({id=471,chapterType=2,chapterIndex=11,regionId=1001,isShow=0,chapterList=0,chapterName="挑战关第二阶段",chapterInfo="挑战关第二阶段",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=1470203}},mt),
    ["472"]=setmetatable({id=472,chapterType=2,chapterIndex=12,regionId=1001,isShow=0,chapterList=0,chapterName="挑战关第三阶段",chapterInfo="挑战关第三阶段",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=1471204}},mt),
    ["473"]=setmetatable({id=473,chapterType=2,chapterIndex=13,regionId=1001,isShow=0,chapterList=0,chapterName="挑战关第四阶段",chapterInfo="挑战关第四阶段",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=1472205}},mt),
    ["461"]=setmetatable({id=461,chapterType=4,chapterIndex=1,regionId=1001,isShow=1,chapterList=0,chapterName="支线章节",chapterInfo="间章",chapterInfoEn="",chapterStory="",chapterConditionId={[1]=101},unlockLevel=0,chapterBgTex="",chapterIcon="",chaperColleIcon="",chapterPic="",chapterPicture="",startVideo="",startStory=0,landmarkId=0,startPic="",chapterPictureMan="bg-cp2",chapterPictureWoman="bg-cp2"},mt),
    ["800"]=setmetatable({id=800,chapterType=8,chapterIndex=0,regionId=0,isShow=1,chapterList=0,chapterName="异梦·篇章一",chapterInfo="深空歧梦",chapterInfoEn="EVENT",chapterStory="",chapterConditionId={[1]=1}},mt),
    ["801"]=setmetatable({id=801,chapterType=8,chapterIndex=0,regionId=0,isShow=1,chapterList=0,chapterName="异梦·篇章二",chapterInfo="金色梦乡",chapterInfoEn="EVENT",chapterStory="",chapterConditionId={[1]=1}},mt),
    ["901"]=setmetatable({id=901,chapterType=8,chapterIndex=0,regionId=0,isShow=1,chapterList=0,chapterName="赛季活动2-资源关章节",chapterInfo="",chapterInfoEn="EVENT",chapterStory="",chapterConditionId={[1]=1}},mt),
}
--生成获取数据的方法
---@return MainChapter
function GetMainChapterData(id)
    return MainChapter_Xls[tostring(id)]
end
--自动生成注释
---@class MainChapter : table 
---@field id number
---@field chapterType number
---@field chapterIndex number
---@field regionId number
---@field isShow number
---@field chapterList number
---@field chapterName string
---@field chapterInfo string
---@field chapterInfoEn string
---@field chapterStory string
---@field chapterConditionId table
---@field unlockLevel number
---@field chapterBgTex string
---@field chapterIcon string
---@field chaperColleIcon string
---@field chapterPic string
---@field chapterPicture string
---@field startVideo string
---@field startStory number
---@field landmarkId number
---@field startPic string
---@field chapterPictureMan string
---@field chapterPictureWoman string
---@field startPicMan string
---@field startPicWoman string
---@field iosDefaultValue number
