---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hejincheng.
--- DateTime: 2022/7/9 15:09
--- 技能数据

---@class SkillCollectData : table
---@field ownerUid number 数据归属玩家id
---@field dictId number 使用者dictId
---@field unitType number 使用者类型
---@field skillId number 使用技能id
SkillCollectData = class(nil, "SkillCollectData")

function SkillCollectData:ctor(_ownerUid, _dictId, _unitType, _skillId)
    self.ownerUid = _ownerUid
    self.dictId = _dictId
    self.unitType = _unitType
    self.skillId = _skillId
end